openfun/joanie

src/backend/joanie/core/factories.py
src/backend/joanie/lms_handler/backends/dummy.py
src/backend/joanie/lms_handler/tests/test_backend_dummy.py
src/backend/joanie/settings.py

We need to be able to mock our LMS Backend interface to test easily our apps.

✅(lms_handler) add a dummy lms backend for tests

---

CHANGELOG.md
Dockerfile

As a best practice, it is recommended to upgrade image packages on build to be sure to have last security updates.
https://pythonspeed.com/articles/security-updates-in-docker/

👷(Dockerfile) upgrade packages on build

---

src/backend/setup.cfg

Renovate Python Dependency PR seems stucked so let's try to create it manually to see if next time all will work fine..
Update dependencies
| Dependency  | From | To |
| --------  | :------------------- | ---------------------: |
| arrow | 1.0.3      | 1.1.0                  | 
| django      | 3.2 | 3.2.4             | 
| django-countries      | 7.1 | 7.2.1             | 
| djangorestframework-simplejwt      | 4.6.0 | 4.7.1             | 
| sentry-sdk      | 1.0.0 | 1.1.0             | 
| flake8      | 3.9.1 | 3.9.2             | 
| ipdb      | 0.13.7 | 0.13.9             | 
| ipython      | 7.22.0 | 7.24.1             | 
| pyfakefs | 4.4.0 | 4.5.0 |
| pylint-django | 2.4.3 | 2.4.4 |
| pylint | 2.7.4 | 2.8.3 |
| pytest-cov | 2.11.1 | 2.12.1 |
| pytest-django | 4.2.0 | 4.4.0 |
| pytest | …

⬆️(dependencies) update python dependencies

---

src/backend/joanie/core/models/products.py
src/backend/joanie/settings.py
src/backend/setup.cfg

Upgrade marion to version 0.3.2 and howard to version 0.2.5

⬆️(deps) upgrade marion and howard

---

README.md

Previous PR has been unexpectedly merged without corrections.

✏️(project) fix README typos

---

src/tray/templates/services/app/_env.yml.j2

We previously fully remove _env.yml.j2 file but it appears it breaks tray.

🔧(tray) restore _env.yml.j2 file

---

CHANGELOG.md
Dockerfile
Makefile

Add Makefile entry to acces postgresql docker in cli using: `make psql`

Add make dbshell cmd to access database in cli

---

Makefile
src/backend/joanie/core/management/commands/loaddatafake.py

* resetdb: flush database and recreate django super user "admin".
* create an demo organization.
* give access to the organisation to admin user.
* set demo organization as cours organization.
* add 10 more courses to have a minimal liste.
* add 10 more products to have a minimal liste.
* give access to all courses to admin user.

🧑‍💻(backend) add command sandbox-dev

---

src/frontend/admin/src/layouts/dashboard/DashboardLayout.tsx
src/frontend/admin/src/layouts/dashboard/config.ts
src/frontend/admin/src/layouts/dashboard/header/DashboardLayoutHeader.tsx
src/frontend/admin/src/layouts/dashboard/nav/DashboardNav.tsx
src/frontend/admin/src/pages/_app.tsx
src/frontend/admin/src/theme/JoanieThemeProvider.tsx
src/frontend/admin/src/theme/types.ts

We were not able to be able to add variables in the theme or to modify the colors of the themes
Added MUI customization stack
Close #287

✨(frontend) add MUI theming stack

---

Makefile
README.md
env.d/development/common
src/backend/joanie/core/admin.py
src/backend/joanie/core/factories.py
src/backend/joanie/demo/defaults.py
src/backend/joanie/demo/management/commands/create_demo.py
src/backend/joanie/payment/admin.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_models_enrollment.py
src/backend/joanie/tests/demo/test_commands_create_demo.py
src/backend/setup.cfg

We want to be able to generate a demo database for testing purposes. It should allow creating big amounts of objects : millions of users, tens of millions of enrollments,...
Add a management command `create_demo` that creates random objects in database, making use of bulk insertion for models that we expect to create in huge quantities.
I tested this script on my laptop to create a database with 10M users and 200M enrollments.

Add management command to create demo data in bulk

---

src/backend/joanie/core/api/client.py
src/backend/joanie/tests/core/test_api_course_wishes.py

Currently, we cannot request course's wishes through a course code, it only works with a course id. Actually, within `wish` action, we only retrieved course
object through its `pk`.

🐛(core) fix wish api endpoint with course code

---

CHANGELOG.md
src/backend/joanie/core/api/admin.py
src/backend/joanie/core/api/client.py
src/backend/joanie/core/models/accounts.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_admin_users.py
src/backend/joanie/tests/core/test_api_users.py
src/backend/joanie/tests/core/test_models_user.py
src/backend/joanie/urls.py

Added route detailing currently logged in user with staff and admin status, and status on accesses

✨(backend) Add route detailing current user

---

CHANGELOG.md
env.d/development/common
src/backend/joanie/core/views.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_views_backoffice_redirect.py
src/backend/joanie/urls.py
src/frontend/admin/.env.example
src/frontend/admin/jest.env.js
src/frontend/admin/mocks/handlers/auth/index.ts
src/frontend/admin/mocks/handlers/index.ts
src/frontend/admin/src/contexts/auth/AuthContext.tsx
src/frontend/admin/src/contexts/auth/AuthProvider.tsx
src/frontend/admin/src/layouts/dashboard/nav/account/DashboardLayoutNavAccount.tsx
src/frontend/admin/src/pages/_app.tsx
src/frontend/admin/src/services/http/HttpService.ts
src/frontend/admin/src/services/repositories/auth/AuthRepository.ts
src/frontend/admin/src/types/auth.ts
src/frontend/admin/src/types/utils.ts
src/frontend/admin/src/utils/routes/path.spec.tsx
src/frontend/admin/src/utils/routes/path.ts

Currently we want to use django admin authentication. However, we need redirects once connected or disconnected.

✨(core) add login redirection 

---

src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/test_models_order.py

Currently, we are not able to submit a pending order that is weird. Indeed, an order goes in pending state, when the payment has failed. So the user should be able to resubmit this order to retry a payment. Furthermore, on submit, we copy product target course relation into order, in order to prevent issues we must exec this copy only when order is draft.

🐛(core) allow to submit a pending order

---

CHANGELOG.md
src/backend/joanie/core/api/admin.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_products.py
src/backend/joanie/urls.py

Added a route that allow to add a target course to a product
Add routes to link and unlink target courses from a product and add details to detailed view of products

✨(backend) add target course route and list view for products

---

CHANGELOG.md
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_order.py

Our frontend need's to query list of order of differents state. Ex: give me all orders validated or waiting for validation: validated, pending, submitted

✨(backend) change order's state filter change from ChoiceFilter to MultipleChoiceFilter

---

.circleci/config.yml
CHANGELOG.md
Makefile
src/backend/setup.cfg

mypy is not used and blocks the implementation of a feature that prompted its removal

➖(linter) removed mypy

---

CHANGELOG.md
docs/reference/workflows.md

Adding documentation clarifying the Order FSM workflow

📝(doc) add mermaid graph for order workflow

---

CHANGELOG.md
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_course.py

Add the possibility to filter courses by type of linked product

✨(backend) add filter courses by product type

---

CHANGELOG.md
src/backend/joanie/demo/management/commands/create_dev_demo.py
src/backend/joanie/tests/demo/test_commands_create_dev_demo.py

- add order of every state
- add a credit card
- add order target courses

🧑‍💻(backend) demo-dev improvments 

---

CHANGELOG.md
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/core/test_api_enrollment.py

note: parent PR:  #439 
api/client: richie needs more than contract and contract definition ids

✨(backend) Order and Product serializer return Contract and ContractDefinition objects

---

src/frontend/admin/src/components/presentational/card/LinkCard.tsx
src/frontend/admin/src/layouts/dashboard/nav/header/DashboardNavHeader.tsx
src/frontend/admin/src/pages/admin/index.tsx
src/frontend/admin/src/pages/index.tsx
src/frontend/admin/src/translations/pages/home/cardTranslations.ts
src/frontend/admin/src/utils/pages/home/homeCardsData.tsx
src/frontend/admin/src/utils/routes/path.ts

Currently, no home page is available. We therefore decided to add a home page with shortcuts to create the different resources available.

✨(frontend) add home page

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_order.py

OrderSerializer needs to return enrollment.
Use EnrollmentLightSerializer in OrderSerializer

✨(backend) update OrderSerializer

---

src/backend/joanie/core/factories.py
src/backend/joanie/demo/management/commands/create_dev_demo.py
src/backend/joanie/tests/demo/test_commands_create_dev_demo.py

Demo dev: We need orders with contracts signed and unsigned for development in richie
api/client: richie needs more than contract and contract definition ids

🧑‍💻(backend) dev_demo: add contract

---

.circleci/config.yml
src/frontend/admin/.eslintrc.json
src/frontend/admin/.gitignore
src/frontend/admin/package.json
src/frontend/admin/playwright.config.ts
src/frontend/admin/src/components/presentational/table/TableComponent.tsx
src/frontend/admin/src/contexts/auth/AuthProvider.tsx
src/frontend/admin/src/hooks/useResponsive.tsx
src/frontend/admin/src/layouts/dashboard/nav/DashboardNav.tsx
src/frontend/admin/src/services/repositories/courses-runs/CoursesRunsRepository.ts
src/frontend/admin/src/tests/product/ProductTestScenario.ts
src/frontend/admin/src/tests/product/product.test.e2e.ts
src/frontend/admin/src/tests/useMockResource.ts
src/frontend/admin/src/tests/useResourceHandler.ts
src/frontend/admin/src/utils/forms.ts
src/frontend/admin/yarn.lock

Currently, backoffice test coverage is limited for user test scenarios. we therefore decided to add playwright to cover its tests.

✅(frontend) init playwright stack 

---

src/frontend/admin/mocks/handlers/contract-definitions/index.ts
src/frontend/admin/mocks/handlers/index.ts
src/frontend/admin/src/components/presentational/inputs/markdown/MardownComponent.tsx
src/frontend/admin/src/components/templates/contract-definition/form/ContractDefinitionForm.spec.tsx
src/frontend/admin/src/components/templates/contract-definition/form/ContractDefinitionForm.tsx
src/frontend/admin/src/components/templates/contract-definition/list/ContractsDefinitionsList.spec.tsx
src/frontend/admin/src/components/templates/contract-definition/list/ContractsDefinitionsList.tsx
src/frontend/admin/src/hooks/useContractDefinitions/useContractDefinitions.ts
src/frontend/admin/src/layouts/dashboard/nav/config.tsx
src/frontend/admin/src/pages/admin/contracts-definitions/[id]/edit.tsx
src/frontend/admin/src/pages/admin/contracts-definitions/create.tsx
src/frontend/admin/src/pages/admin/contracts-definitions/index.tsx
src/frontend/admin/src/pages/admin/contracts-definitions/list.tsx
src/frontend/admin/src/services/api/models/ContractDefinition.ts
src/frontend/admin/src/services/factories/contract-definition/index.ts
src/frontend/admin/src/services/repositories/contract-definition/ContractDefinitionRepository.ts
src/frontend/admin/src/translations/common/languageTranslations.ts
src/frontend/admin/src/translations/pages/contracts-definitions/breadcrumbsTranslations.ts
src/frontend/admin/src/translations/pages/home/cardTranslations.ts
src/frontend/admin/src/utils/pages/home/homeCardsData.tsx
src/frontend/admin/src/utils/routes/path.ts

The notion of contract definition did not yet exist in the BO. We therefore add the possibility of listing, adding and editing a ContractDefinition

✨(frontend) add contract definitions CRUD 

---

src/backend/joanie/core/api/admin.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/api/admin/course-product-relations/test_create.py
src/backend/joanie/tests/core/api/admin/course-product-relations/test_update.py
src/backend/joanie/tests/swagger/admin-swagger.json

As a CourseProductRelation may be related to many organizations, create, update and partial update should have an array of organization ids in their parameters.

🩹(backend) many organizations in CourseProductRelation API

---

src/frontend/admin/package.json
src/frontend/admin/src/components/presentational/modal/AlertModal.tsx
src/frontend/admin/src/components/presentational/table/TableComponent.spec.tsx
src/frontend/admin/src/components/presentational/table/useTableResourcePagination.spec.tsx
src/frontend/admin/src/components/presentational/wizard/Wizard.spec.tsx
src/frontend/admin/src/components/templates/contract-definition/form/ContractDefinitionForm.spec.tsx
src/frontend/admin/src/components/templates/courses/form/CourseForm.spec.tsx
src/frontend/admin/src/components/templates/courses/form/product-relation/CourseProductRelationForm.spec.tsx
src/frontend/admin/src/components/templates/products/form/ProductForm.spec.tsx
src/frontend/admin/yarn.lock

Currently test suite frontend admin is flaky. Several tests times out and there are several warnings. This PR tries to address all those issues.

✅(frontend/admin) fix flaky test issues

---

src/frontend/admin/.eslintrc.json
src/frontend/admin/jest.env.js
src/frontend/admin/src/components/presentational/modal/FullScreenModal.tsx
src/frontend/admin/src/components/presentational/table/TableComponent.tsx
src/frontend/admin/src/components/presentational/table/usePaginatedTableResource.ts
src/frontend/admin/src/components/templates/certificates-definitions/inputs/search/CertificateSearch.tsx
src/frontend/admin/src/components/templates/certificates-definitions/modals/CreateOrEditCertificationModal.tsx
src/frontend/admin/src/components/templates/courses-runs/form/CourseRunForm.tsx
src/frontend/admin/src/components/templates/courses-runs/form/translations.ts
src/frontend/admin/src/components/templates/courses-runs/list/CourseRunsListColumns.tsx
src/frontend/admin/src/components/templates/courses-runs/list/CoursesRunsList.tsx
src/frontend/admin/src/components/templates/courses/form/CourseForm.spec.tsx
src/frontend/admin/src/components/templates/courses/form/CourseForm.tsx
src/frontend/admin/src/components/templates/courses/form/sections/target-course-runs/CourseFormTargetCourseRunsSection.tsx
src/frontend/admin/src/components/templates/courses/form/translations.ts
src/frontend/admin/src/components/templates/courses/inputs/search/CourseSearch.tsx
src/frontend/admin/src/components/templates/courses/modals/CreateOrEditCourseModal.tsx
src/frontend/admin/src/components/templates/organizations/inputs/search/OrganizationSearch.tsx
src/frontend/admin/src/components/templates/organizations/modals/CreateOrEditOrganizationModal.tsx
src/frontend/admin/src/components/templates/products/form/ProductForm.spec.tsx
src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductFormTargetCoursesSection.tsx
src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductTargetCourseRelationForm.tsx
src/frontend/admin/src/components/templates/products/form/translations.ts
src/frontend/admin/src/pages/admin/courses-runs/list.tsx
src/frontend/admin/src/pages/admin/products/list.tsx
src/frontend/admin/src/services/api/models/Course.ts
src/frontend/admin/src/styles/globals.scss
src/frontend/admin/src/utils/array.ts
src/frontend/admin/src/utils/arrayUtils.spec.tsx
src/frontend/admin/tsconfig.json

When you add a resource, some of them depend on other resources. We therefore want to facilitate the user journey. To do this, we add the ability to create/edit resources dynamically in a form.
https://github.com/openfun/joanie/assets/19410531/157b9150-a4a0-4553-8b1e-43b021dfe323
https://github.com/openfun/joanie/assets/19410531/2cf45ca9-8882-4c78-a21a-33eb852ab54c
https://github.com/openfun/joanie/assets/19410531/d240e599-a35c-440f-8515-e35871335cca
https://github.com/openfun/joanie/assets/19410531/eceff017-f164-44ef-8897-5b443eafe969

✨(frontend) add shortcut for add  or edit ressource

---

src/backend/joanie/demo/management/commands/create_dev_demo.py

ProductFactory create a product with a contract_definition by default. For our test data, we don't want all our product to be related to a contract_definition

🧑‍💻(frontend) Contract in demo-dev

---

.circleci/config.yml
docker-compose.yml
src/backend/locale/es_ES/LC_MESSAGES/django.po
src/backend/locale/fr_CA/LC_MESSAGES/django.po
src/backend/locale/fr_FR/LC_MESSAGES/django.po

This is currently impossible to update translation from Crowdin. This PR fixes that
Description...

⬆️(crowdin) upgrade crowdin image to latest version

---

.circleci/config.yml
.dockerignore
.gitignore
CHANGELOG.md
docker/files/admin/etc/nginx/conf.d/default.conf
docker/images/admin/Dockerfile
src/backend/joanie/core/middleware.py
src/backend/joanie/settings.py
src/frontend/admin/next.config.js
src/frontend/admin/package.json
src/frontend/admin/playwright.config.ts
src/tray/templates/services/admin/configs/admin.conf.j2
src/tray/templates/services/admin/configs/healthcheck.conf.j2
src/tray/templates/services/admin/deploy.yml.j2
src/tray/templates/services/admin/ingress.yml.j2
src/tray/templates/services/admin/static-svc.yml.j2
src/tray/templates/services/admin/svc.yml.j2
src/tray/templates/services/app/_deploy_base.yml.j2
src/tray/templates/services/app/deploy_app.yml.j2
src/tray/templates/services/app/deploy_celery.yml.j2
src/tray/templates/services/nginx/configs/joanie.conf.j2
src/tray/vars/all/main.yml

We want to deploy the frontend build on our cluster. Unfortunately
we can't inject environment variable at the runtime. So we decided in a
first version to export in full static with our preprod ou production
url.

Deploy admin application

---

src/frontend/admin/src/components/templates/organizations/form/OrganizationForm.tsx
src/frontend/admin/src/components/templates/organizations/form/translations.ts
src/frontend/admin/src/hooks/useOrganizations/useOrganizations.tsx
src/frontend/admin/src/services/api/models/Organization.ts
src/frontend/admin/src/services/factories/organizations/index.ts
src/frontend/admin/src/services/repositories/organization/OrganizationRepository.ts
src/frontend/admin/src/tests/mocks/organizations/organization-mock.ts
src/frontend/admin/src/tests/organization/organization.test.e2e.ts

It is not possible to select the country of the organization. We therefore add a select to the form.

✨(frontend) add country input

---

src/frontend/admin/src/components/presentational/menu-popover/MenuPopover.spec.tsx
src/frontend/admin/src/components/presentational/menu-popover/MenuPopover.tsx
src/frontend/admin/src/components/presentational/table/TableDefaultActions.tsx
src/frontend/admin/src/components/templates/courses-runs/form/CourseRunForm.tsx
src/frontend/admin/src/components/templates/courses-runs/list/CoursesRunsList.tsx
src/frontend/admin/src/components/templates/courses/form/sections/product-relation/CourseProductRelationRow.tsx
src/frontend/admin/src/components/templates/products/form/sections/course-product-relations/ProductFormCourseProductRelations.tsx
src/frontend/admin/src/hooks/useCopyToClipboard.tsx
src/frontend/admin/src/services/api/models/CourseRun.ts
src/frontend/admin/src/services/api/models/Relations.ts
src/frontend/admin/src/services/factories/courses-runs/index.ts
src/frontend/admin/src/services/factories/courses/index.ts
src/frontend/admin/src/tests/course/course-courseRun-section.test.e2e.ts
src/frontend/admin/src/tests/course/course-product-relation.test.e2e.ts
src/frontend/admin/src/tests/product/product.test.e2e.ts
src/frontend/admin/src/translations/common/commonTranslations.ts

The purpose of this functionality is to be able to easily copy the uri of the entities concerned. We therefore add an option to be able to copy this link to the clipboard.

✨(frontend) add copy to clipboard

---

src/frontend/admin/src/components/presentational/hook-form/RHFDateTimePicker.tsx
src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductFormTargetCourseRow.tsx
src/frontend/admin/src/services/factories/courses/index.ts
src/frontend/admin/src/tests/certificate-definitions/certificate-definition.test.e2e.ts
src/frontend/admin/src/tests/course-run/course-run.test.e2e.ts
src/frontend/admin/src/tests/product/product.test.e2e.ts

Several tests are flaky. Usually related to an animation/request not finished. There may therefore be several elements on the page or not yet present.

✅(frontend) fix flacky tests

---

src/backend/joanie/core/serializers/admin.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_api_admin_course_access.py
src/backend/joanie/tests/core/test_api_admin_courses.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/core/test_api_admin_organization_access.py
src/backend/joanie/tests/core/test_api_admin_organizations.py
src/backend/joanie/tests/core/test_api_admin_users.py
src/backend/joanie/tests/swagger/admin-swagger.json

The back office needs several improvement about the admin order endpoint to display information so we complete admin order serializers and complete some related serializers.

✨(backend) complete admin order api

---

src/backend/joanie/core/factories.py
src/backend/joanie/demo/management/commands/create_dev_demo.py
src/backend/joanie/tests/demo/test_commands_create_dev_demo.py

We need data for every possible signed state of a contract

🧑‍💻(backend) add contract data to demo-dev

---

src/frontend/admin/package.json
src/frontend/admin/public/mockServiceWorker.js
src/frontend/admin/src/components/presentational/table/TableComponent.tsx
src/frontend/admin/src/components/templates/orders/list/OrdersList.tsx
src/frontend/admin/src/components/templates/orders/view/OrderView.tsx
src/frontend/admin/src/components/templates/orders/view/sections/OrderViewInvoiceChildrenRow.tsx
src/frontend/admin/src/components/templates/orders/view/sections/OrderViewInvoiceSection.tsx
src/frontend/admin/src/components/templates/orders/view/translations.tsx
src/frontend/admin/src/components/templates/users/inputs/search/UserSearch.spec.tsx
src/frontend/admin/src/hooks/useOrders/useOrders.tsx
src/frontend/admin/src/layouts/dashboard/nav/config.tsx
src/frontend/admin/src/pages/admin/orders/[id]/view.tsx
src/frontend/admin/src/pages/admin/orders/index.tsx
src/frontend/admin/src/pages/admin/orders/list.tsx
src/frontend/admin/src/services/api/models/Enrollment.ts
src/frontend/admin/src/services/api/models/Order.ts
src/frontend/admin/src/services/api/models/User.ts
src/frontend/admin/src/services/factories/orders/index.ts
src/frontend/admin/src/services/factories/users/index.ts
src/frontend/admin/src/services/repositories/orders/OrderRepository.ts
src/frontend/admin/src/tests/orders/OrderListItemTestScenario.ts
src/frontend/admin/src/tests/orders/OrderTestScenario.ts
src/frontend/admin/src/tests/orders/orders.test.e2e.ts
src/frontend/admin/src/translations/common/commonTranslations.ts
src/frontend/admin/src/translations/pages/orders/breadcrumbsTranslations.ts
src/frontend/admin/src/utils/routes/path.ts

To make it easier to view orders, we are adding a list as well as a detailed view of an order (read only)

✨(frontend) feature orders

---

CHANGELOG.md
docs/moodle.md
src/backend/joanie/core/factories.py
src/backend/joanie/lms_handler/backends/moodle.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_models_enrollment.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/lms_handler/test_backend_moodle.py
src/backend/joanie/tests/lms_handler/test_handler.py
src/backend/pyproject.toml

Adds a moodle LMS backend
Moodlepy is used for now, but needs a PR to be merged.

Add moodle LMS backend

---

src/frontend/admin/src/components/presentational/hook-form/RHFSelect.tsx
src/frontend/admin/src/components/presentational/translatable-content/TranslatableContent.tsx
src/frontend/admin/src/components/templates/certificates-definitions/form/CertificateDefinitionForm.tsx
src/frontend/admin/src/components/templates/certificates-definitions/inputs/RHFCertificateDefinitionTemplate.tsx
src/frontend/admin/src/contexts/i18n/TranslationsProvider/TranslationsProvider.tsx
src/frontend/admin/src/layouts/dashboard/nav/config.tsx
src/frontend/admin/src/services/api/models/CertificateDefinition.ts
src/frontend/admin/src/services/http/HttpService.ts
src/frontend/admin/src/services/repositories/certificate-definition/CertificateDefinitionRepository.ts
src/frontend/admin/src/utils/constants.ts

The template select has only one value "Default" but it exists two certificate templates so administrator should be able to select one of them.
close #591

✨(frontend) add certificate definition template

---

src/backend/joanie/core/models/courses.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_course_runs.py
src/backend/joanie/tests/swagger/admin-swagger.json
src/backend/joanie/tests/swagger/swagger.json

The field `state` was not bound to the CourseRunSerializer but backoffice needs this information.

✨(backend) bind state field into CourseRunSerializer

---

src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_utils_image_to_base64.py
src/backend/pyproject.toml

Some small improvements for developers.

Dx improvements

---

CHANGELOG.md
src/backend/joanie/core/static/joanie/css/certificate/verify.css
src/backend/joanie/core/templates/certificate/verify.html
src/backend/joanie/core/views/__init__.py
src/backend/joanie/core/views/certificate.py
src/backend/joanie/core/views/debug.py
src/backend/joanie/core/views/redirect.py
src/backend/joanie/tests/core/test_views_certificate_verify.py
src/backend/joanie/urls.py

Add a view to allow user to check if a generated certificate is genuine.

✨(backend) certificate validation view

---

src/frontend/admin/src/components/templates/products/form/sections/main/ProductFormMain.tsx

Currently it is not possible to translate a product. We therefore add the tabs present in the other forms
Close #592

✨(frontend) add translation tabs in ProductFormMain

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/api/organizations/test_list.py
src/backend/joanie/tests/swagger/swagger.json

Our client api consumers should be able to filter out organizations through a course product relation id.

✨(backend) allow to filter organization through course product relation

---

src/frontend/admin/src/components/templates/products/form/sections/main/ProductFormMain.tsx
src/frontend/admin/src/components/templates/products/form/sections/main/financial/ProductFormFinancial.tsx
src/frontend/admin/src/tests/product/product.test.e2e.ts

Following bugs concerning automatic saving, we put back the submit button first.
We will work on automatic backup later.

✨(frontend) add submit button to product form

---

src/frontend/admin/src/components/presentational/hook-form/RHFProvider.tsx
src/frontend/admin/src/components/presentational/modal/AlertModal.tsx
src/frontend/admin/src/components/presentational/wizard/Wizard.tsx
src/frontend/admin/src/components/templates/certificates-definitions/form/CertificateDefinitionForm.tsx
src/frontend/admin/src/components/templates/contract-definition/form/ContractDefinitionForm.tsx
src/frontend/admin/src/components/templates/courses-runs/form/CourseRunForm.tsx
src/frontend/admin/src/components/templates/courses/form/CourseForm.tsx
src/frontend/admin/src/components/templates/organizations/form/OrganizationForm.tsx
src/frontend/admin/src/components/templates/products/form/sections/main/ProductFormMain.tsx
src/frontend/admin/src/translations/common/commonTranslations.ts

Currently, if you have an unsaved modified form and you want to change pages or
refresh the page, no message warns you that the form is not saved. 
Important : The tests will be written in another PR. You need to set up the playwright component test stack.

✨(frontend) add management of unsaved forms

---

src/backend/joanie/core/api/client.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_create.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_list.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_retrieve.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_update.py
src/backend/joanie/tests/core/api/organizations/test_api_organizations_contract.py
src/backend/joanie/tests/core/test_api_courses_contract.py
src/backend/joanie/tests/core/test_models_order.py

Some __init__.py files are missing, which prevents pylint to lint files.

Fix pylint

---

src/frontend/admin/src/components/templates/products/form/sections/main/ProductFormMain.tsx

An error during a previous merge deleted a prop

🚑️(frontend) fix product unsaved alert

---

src/backend/joanie/edx_imports/tasks/users.py
src/backend/joanie/tests/edx_imports/test_import_users.py

It appears that we may have very long user names in Open edX. We trim them, and skip them if still too long.
The same process is applied to email and userprofile name.

🐛(backend) strip user data

---

src/frontend/admin/src/components/templates/organizations/form/OrganizationForm.tsx
src/frontend/admin/src/components/templates/organizations/form/sections/OrganizationAddressForm.tsx
src/frontend/admin/src/components/templates/organizations/form/translations.ts
src/frontend/admin/src/hooks/useOrganizations/useOrganizations.tsx
src/frontend/admin/src/hooks/useResources/useResourcesRoot.ts
src/frontend/admin/src/services/api/models/Organization.ts
src/frontend/admin/src/services/repositories/organization/OrganizationRepository.ts
src/frontend/admin/src/tests/organization/organization.test.e2e.ts

On the database side, an address table has been added to the organization model.
We therefore add this attribute in the front model and add an OrganizationAddressForm

✨(frontend) add organization address

---

CHANGELOG.md
src/frontend/admin/src/components/templates/orders/view/OrderView.tsx
src/frontend/admin/src/components/templates/orders/view/sections/OrderViewContractSection.tsx
src/frontend/admin/src/components/templates/orders/view/sections/OrderViewInvoiceSection.tsx
src/frontend/admin/src/components/templates/orders/view/translations.tsx
src/frontend/admin/src/services/api/models/Order.ts
src/frontend/admin/src/services/factories/orders/index.ts
src/frontend/admin/src/tests/orders/orders.test.e2e.ts

The contract section is missing in the order view. We therefore add this section
with all the necessary information.

✨(frontend) add contract section to order view

---

.circleci/config.yml
CHANGELOG.md
src/frontend/admin/.gitignore
src/frontend/admin/package.json
src/frontend/admin/playwright-ct.config.ts
src/frontend/admin/playwright/index.html
src/frontend/admin/playwright/index.tsx
src/frontend/admin/src/components/presentational/hook-form/RHFAutocomplete.tsx
src/frontend/admin/src/components/presentational/hook-form/RHFProvider.tsx
src/frontend/admin/src/components/presentational/hook-form/RHFRadioGroup.tsx
src/frontend/admin/src/components/presentational/modal/Modal.tsx
src/frontend/admin/src/components/testing/presentational/filters/SearchFilters/SearchFilters.spec.e2e.tsx
src/frontend/admin/src/components/testing/presentational/filters/SearchFilters/SearchFiltersWrapperTest.tsx
src/frontend/admin/src/components/testing/presentational/hook-form/RHFProvider/RHFProvider.spec.e2e.tsx
src/frontend/admin/src/components/testing/presentational/hook-form/RHFProvider/RHFProviderTestWrapper.tsx
src/frontend/admin/yarn.lock

Some components are not tested. We therefore add the possibility of doing component testing with playwright.

✅(frontend) Test playwright component stack

---

CHANGELOG.md
src/frontend/admin/src/components/templates/courses-runs/list/CourseRunsListColumns.tsx
src/frontend/admin/src/components/templates/courses-runs/list/CoursesRunsList.tsx
src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductFormTargetCourseRow.tsx
src/frontend/admin/src/tests/course-run/course-run-list.test.e2e.ts
src/frontend/admin/src/tests/course/course-courseRun-section.test.e2e.ts
src/frontend/admin/src/tests/course/course.test.e2e.ts
src/frontend/admin/src/tests/product/product.test.e2e.ts
src/frontend/admin/src/tests/utils.ts

Several small disturbing points are still present in the back office.

✨(frontend) several small modifications

---

CHANGELOG.md
src/backend/joanie/core/api/admin.py
src/backend/joanie/core/filters/admin.py
src/backend/joanie/core/filters/base.py
src/backend/joanie/tests/core/test_api_admin_certificate_definitions.py
src/backend/joanie/tests/core/test_api_admin_contract_definitions.py
src/backend/joanie/tests/core/test_api_admin_course_runs.py
src/backend/joanie/tests/core/test_api_admin_courses.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/core/test_api_admin_organizations.py
src/backend/joanie/tests/core/test_api_admin_products.py
src/backend/joanie/tests/core/test_api_admin_users.py
src/backend/joanie/tests/swagger/admin-swagger.json

We want to filter all resources list on the admin through their pk.
A new filter MultipleValueFilter is added allowing to filter a field
with multiple values.
Solved #682

✨(back) filter admin resources list through their pk

---

CHANGELOG.md
src/frontend/admin/src/components/presentational/tabs/TabsComponent.tsx
src/frontend/admin/src/components/presentational/translatable-content/TranslatableContent.tsx
src/frontend/admin/src/components/presentational/wizard/Wizard.tsx
src/frontend/admin/src/components/templates/courses/form/CourseForm.tsx
src/frontend/admin/src/components/templates/courses/form/general/GeneralCourseForm.tsx
src/frontend/admin/src/components/templates/courses/form/sections/product-relation/CourseFormProductRelationsSection.tsx
src/frontend/admin/src/components/templates/courses/form/translations.ts
src/frontend/admin/src/components/templates/organizations/form/OrganizationForm.tsx
src/frontend/admin/src/components/templates/organizations/form/sections/OrganizationAddressForm.tsx
src/frontend/admin/src/components/templates/organizations/form/sections/OrganizationGeneralSection.tsx
src/frontend/admin/src/components/templates/organizations/form/sections/OrganizationMemberSection.tsx
src/frontend/admin/src/components/templates/products/form/ProductForm.tsx
src/frontend/admin/src/components/templates/products/form/sections/course-product-relations/ProductFormCourseProductRelations.tsx
src/frontend/admin/src/tests/course/course-courseRun-section.test.e2e.ts
src/frontend/admin/src/tests/course/course-product-relation.test.e2e.ts
src/frontend/admin/src/tests/course/course.test.e2e.ts
src/frontend/admin/src/tests/organization/organization.test.e2e.ts
src/frontend/admin/src/tests/product/product.test.e2e.ts

Currently, several forms are difficult to read because there are too many sections on the same page, so we decide to arrange them in tabs in order to streamline

✨(frontend) separate multiple forms into tabs

---

CHANGELOG.md
src/frontend/admin/src/components/presentational/button/CloseNotificationButton.tsx
src/frontend/admin/src/components/presentational/button/menu/ButtonMenu.tsx
src/frontend/admin/src/components/presentational/tooltip/ConditionalTooltip.tsx
src/frontend/admin/src/components/templates/orders/buttons/OrderActions.tsx
src/frontend/admin/src/components/templates/orders/view/OrderView.tsx
src/frontend/admin/src/components/templates/orders/view/sections/OrderViewCertificateSection.tsx
src/frontend/admin/src/components/templates/orders/view/translations.tsx
src/frontend/admin/src/components/testing/presentational/button/menu/ButtonMenu.spec.e2e.tsx
src/frontend/admin/src/components/testing/utils.ts
src/frontend/admin/src/hooks/useOrders/useOrders.tsx
src/frontend/admin/src/hooks/useResources/useResourcesRoot.ts
src/frontend/admin/src/pages/_app.tsx
src/frontend/admin/src/services/api/models/Order.ts
src/frontend/admin/src/services/api/models/Product.ts
src/frontend/admin/src/services/factories/orders/index.ts
src/frontend/admin/src/services/factories/product/index.ts
src/frontend/admin/src/services/repositories/orders/OrderRepository.ts
src/frontend/admin/src/tests/orders/OrderTestScenario.ts
src/frontend/admin/src/tests/orders/orders.test.e2e.ts

Addition of the capability to generate a certificate and display its details through the view of an order.

✨(frontend) order generate certificate

---

Makefile
README.md
bin/_config.sh
bin/state
bin/terraform
docker-compose.yml

Docker-compose v1 seems to not work anymore.
Updating to v2 is needed.

⬆️(docker compose) use docker compose v2

---

src/backend/joanie/lms_handler/backends/moodle.py
src/backend/joanie/lms_handler/backends/openedx.py
src/backend/joanie/tests/lms_handler/test_backend_moodle.py
src/backend/joanie/tests/lms_handler/test_backend_openedx.py

In the lms handlers, unwanted exception, mostly on network error, can be thrown and are not managed at all. These exceptions can break a process (like validating a payment). We must manage well these exceptions in every handlers.
Fixes #711

Better manage exception in lms handlers

---

src/backend/joanie/settings.py

Some setting were missing to be able to enable course run synchronization.

🔧(backend) add missing setting to enable course runs sync

---

CHANGELOG.md
docker-compose.yml

normalize network name between richie, joanie and openedx-docker

🔧(docker) update docker network name

---

CHANGELOG.md
src/frontend/admin/.eslintrc.json
src/frontend/admin/src/components/presentational/modal/AlertModal.tsx
src/frontend/admin/src/components/templates/courses-runs/input/search/RHFCourseRunSearch.tsx
src/frontend/admin/src/components/templates/enrollments/buttons/EnrollmentActions.tsx
src/frontend/admin/src/components/templates/enrollments/filters/EnrollmentFilters.tsx
src/frontend/admin/src/components/templates/enrollments/inputs/RHFSelectEnrollmentState.tsx
src/frontend/admin/src/components/templates/enrollments/list/EnrollmentsList.tsx
src/frontend/admin/src/components/templates/enrollments/view/EnrollmentView.tsx
src/frontend/admin/src/components/templates/enrollments/view/translations.tsx
src/frontend/admin/src/hooks/useEnrollments/useEnrollments.tsx
src/frontend/admin/src/layouts/dashboard/nav/config.tsx
src/frontend/admin/src/pages/admin/enrollments/[id]/view.tsx
src/frontend/admin/src/pages/admin/enrollments/index.tsx
src/frontend/admin/src/pages/admin/enrollments/list.tsx
src/frontend/admin/src/services/api/models/Enrollment.ts
src/frontend/admin/src/services/api/models/GeneratedCertificate.ts
src/frontend/admin/src/services/api/models/Order.ts
src/frontend/admin/src/services/factories/enrollments/index.ts
src/frontend/admin/src/services/repositories/enrollments/EnrollmentRepository.ts
src/frontend/admin/src/tests/enrollments/EnrollmentsTestScenario.ts
src/frontend/admin/src/tests/enrollments/enrollments.test.e2e.ts
src/frontend/admin/src/translations/enrollments/enrollment-state.ts
src/frontend/admin/src/translations/pages/enrollments/breadcrumbsTranslations.ts
src/frontend/admin/src/utils/routes/path.ts

Add enrollment pages in order to be able to list, filter, view an enrollment. We also add the possibility of activating or deactivating an enrollment

✨(frontend) add enrollments pages

---

.circleci/config.yml
CHANGELOG.md
src/frontend/admin/src/components/templates/courses-runs/list/CourseRunsListColumns.tsx
src/frontend/admin/src/components/templates/courses/list/CoursesList.tsx
src/frontend/admin/src/components/templates/orders/view/OrderView.tsx
src/frontend/admin/src/components/templates/orders/view/sections/OrderViewCertificateSection.tsx
src/frontend/admin/src/components/templates/orders/view/sections/OrderViewContractSection.tsx
src/frontend/admin/src/components/templates/orders/view/sections/OrderViewInvoiceChildrenRow.tsx
src/frontend/admin/src/components/templates/orders/view/sections/OrderViewInvoiceSection.tsx
src/frontend/admin/src/components/templates/organizations/list/OrganizationsList.tsx
src/frontend/admin/src/tests/course-run/course-run-list.test.e2e.ts
src/frontend/admin/src/tests/course/course-courseRun-section.test.e2e.ts
src/frontend/admin/src/tests/course/course.test.e2e.ts
src/frontend/admin/src/tests/orders/orders-filters.test.e2e.ts
src/frontend/admin/src/tests/orders/orders.test.e2e.ts
src/frontend/admin/src/tests/organization/organization.test.e2e.ts
src/frontend/admin/src/tests/utils.ts
src/frontend/admin/src/utils/dates.tsx
src/frontend/admin/src/utils/testing.ts

We want to improve the use of the BO. We therefore add clickable links in the lists and we format the dates to make it more readable.
https://github.com/openfun/joanie/assets/19410531/9073b8e7-4d39-42b4-8452-5312b005d352

✨(frontend) some improvements

---

CHANGELOG.md
src/backend/joanie/core/api/admin/__init__.py
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/tests/core/test_api_admin_organization_addresses.py

Some of our viewsets can benefit from the class `NestedGenericViewSet`. 
The classes that were eligible for this refactor will be updated.
The custom `NestedGenericViewset` was implemented after some viewsets. Some of those viewsets will finally benefit from this class if eligible.

♻️(refactor) update `GenericViewSet` to `NestedGenericViewSet` for API client and admin viewsets

---

CHANGELOG.md
src/frontend/admin/src/components/presentational/table/TableComponent.tsx
src/frontend/admin/src/components/templates/accesses/list/AccessesList.tsx
src/frontend/admin/src/components/templates/accesses/list/SelectAccess.tsx
src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductFormTargetCoursesSection.tsx

Several layout issues are present in the back office. Like problems displaying a select in a list or missing spacing

💄(frontend) fix many layout issues

---

CHANGELOG.md
src/frontend/admin/src/components/presentational/button/menu/ButtonMenu.tsx
src/frontend/admin/src/components/presentational/menu-popover/CustomMenuItem.tsx
src/frontend/admin/src/components/presentational/menu-popover/MenuPopover.spec.tsx
src/frontend/admin/src/components/presentational/menu-popover/MenuPopover.tsx
src/frontend/admin/src/components/presentational/table/TableComponent.tsx
src/frontend/admin/src/components/presentational/table/TableDefaultActions.tsx
src/frontend/admin/src/components/templates/courses-runs/list/CoursesRunsList.tsx
src/frontend/admin/src/components/templates/courses/form/sections/product-relation/CourseProductRelationRow.tsx
src/frontend/admin/src/services/repositories/course-product-relation/CourseProductRelationRepository.ts
src/frontend/admin/src/tests/course/course.test.e2e.ts

New endpoints have been added to the backend to be able to create a certificate generation job and to check if one already exists. In order to be able to generate several certificates at the same time, we add
the creation of a job on a course product relation

✨(frontend)  generate multiple certificate in syllabus

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

> [!CAUTION]  
> PR blocked by #848
- Add settings configuration for the contract's country calendar to manage the payment schedule and the withdrawal period in days
- Catch all exceptions raised by enroll_user_to_course_run method
- Fix enrollment mode update on order validation

🔖(minor) bump to 2.4.0

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/i18n/locales/es-ES.json
src/frontend/admin/i18n/locales/fr-CA.json
src/frontend/admin/i18n/locales/fr-FR.json
src/frontend/admin/package.json
src/frontend/admin/src/translations/es-ES.json
src/frontend/admin/src/translations/fr-CA.json
src/frontend/admin/src/translations/fr-FR.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Minor bump to 2.5.0
- Do not update OpenEdX enrollment if this one is already up-to-date on the remote lms

🔖(minor) bump to 2.5.0

---

src/frontend/admin/playwright.config.ts
src/frontend/admin/src/tests/course-run/course-run-list.test.e2e.ts
src/frontend/admin/src/tests/course/course-courseRun-section.test.e2e.ts
src/frontend/admin/src/tests/orders/orders.test.e2e.ts

Force locale, to avoid system default locale usage.

✅(frontend) force locale in e2e tests

---

src/backend/joanie/signature/backends/base.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/signature/test_backend_signature_base.py

Dev /merge main

---

src/backend/joanie/core/factories.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/swagger/admin-swagger.json
src/frontend/admin/src/components/templates/orders/list/OrdersList.tsx
src/frontend/admin/src/components/templates/orders/view/OrderView.tsx
src/frontend/admin/src/components/templates/orders/view/translations.tsx
src/frontend/admin/src/services/api/models/Order.ts
src/frontend/admin/src/services/factories/orders/index.ts
src/frontend/admin/src/tests/orders/orders-filters.test.e2e.ts
src/frontend/admin/src/tests/orders/orders.test.e2e.ts

As we have new order states, we need to use them in admin frontend.

🐛(frontend) use new order states

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Minor bump to 2.6.0
- Add management command to fix imported certificates without signatory
- Fix signatories retrieval logic in edx certificate import

🔖(minor) bump to 2.6.0

---

CHANGELOG.md
src/backend/joanie/payment/api.py
src/backend/joanie/tests/payment/test_api_credit_card.py

The list credit card endpoint now returns first the main credit card then all others credit cards sorted by descending creation date.

✨(backend) sort credit card per is_main then creation date

---

src/tray/templates/services/app/cronjob_process_payment_schedules.yml.j2
src/tray/vars/all/main.yml

The extension of the file to declare the cronjob process payment schedule was wrong

🚚(tray) fix cronjob app service extension

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Release Joanie 2.7.1
- Downgrade to django-storages 1.14.3

🔖(patch) release joanie 2.7.1

---

src/backend/joanie/payment/backends/base.py
src/mail/mjml/partial/installment_table.mjml

Not messages contains typo or are not well extracted due to the use of f strings.

🌐(backend) fix typo in messages

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Release joanie 2.9.1
- Manage zero click refused payment

🔖(patch) bump joanie to version 2.9.1

---

.circleci/config.yml
docker-compose.yml

We want to upgrade our Postgres version to 16.4. 
This PR update the CI and compose to match the expected version.
This PR replace #964

⬆️(backend) update postgres to version 16.4

---

src/frontend/admin/src/components/presentational/card/SimpleCard.spec.tsx
src/frontend/admin/src/components/presentational/card/SimpleCard.tsx
src/frontend/admin/src/components/presentational/modal/FullScreenModal.tsx

When enabling dark mode, we forgot to update two components so those ones does not display well in dark.

💄(backoffice) fix dark mode issue

---

.circleci/config.yml
Dockerfile
docker-compose.yml
docker/images/admin/Dockerfile
renovate.json
src/frontend/admin/jest.config.js
src/frontend/admin/jest.polyfills.js
src/frontend/admin/package.json
src/frontend/admin/yarn.lock
src/mail/package.json

Upgrade to the LTS version of node.

⬆️(global) upgrade to node.js 20.x

---

CHANGELOG.md
src/frontend/admin/src/components/templates/orders/list/OrdersList.tsx
src/frontend/admin/src/services/api/models/Order.ts
src/frontend/admin/src/services/factories/orders/index.ts
src/frontend/admin/src/tests/orders/orders.test.e2e.ts

We want to clearly see last updated orders in admin frontend.

✨(frontend) add updated_on to orders list

---

.circleci/config.yml

Setup circle ci test reporting.

💚(circleci) setup tests reporting

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Bump joanie to version 2.14.1
- Take in account `error` installment in debit logic
- Add missing field `updated_on` to `AdminOrderLightSerializer`
- Fix payment check before retrying

🔖(chore) bump to 2.14.1

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Bump joanie to version 2.15.0
- JOANIE_LMS_BACKENDS is now configurable through env vars as a JSON string array of LMS Backends

🔖(chore) bump to 2.15.0

---

src/backend/joanie/core/utils/newsletter/sarbacane.py

In some case, Sarbacane could return 404 errors as its server data are not yet updated while it sends an event on your webhook. So we implement a retry strategy for Sarbacane API calls using requests Session and HTTPAdapter. The changes include:
- Configuring retry for specific HTTP status codes
- Increasing request timeout to 15 seconds
- Using a shared session with mounted adapters for consistent retry behavior

🩹(backend) set retry strategy on Sarbacane GET requests

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Release Joanie 2.17.1
Fixed:
- Allow to configure the Sarbacane API retry total and backoff factor from environment variables

🔖(chore) bump to 2.17.1

---

src/backend/joanie/tests/core/test_api_admin_order_group.py

Fixing a flaky test on the order group list. New ordering rule was added to the model side through the position field.

✅(backend) fix flaky test for order group list

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

- Add course offer information into course webhook synchronization payload
- Update organization assignation logic to ignore order with pending signature or without payment method defined.

🔖(chore) bump to 2.18.0

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

- Downgrade `djangorestframework` to 3.15.2 to fix payzen notifications

🔖(chore) bump to 2.18.1

---

src/backend/joanie/tests/payment/test_backend_lyra_handle_notification.py
src/backend/joanie/tests/payment/test_backend_lyra_old.py

Split payzen tests

---

CHANGELOG.md
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/api/admin/orders/test_export.py
src/backend/joanie/tests/demo/test_commands_create_dev_demo.py
src/backend/joanie/tests/testing_utils.py

Add "Discount" column for Order csv export

:sparkles:(backend) add discount column in csv Orders export

---

src/backend/joanie/core/utils/offering.py
src/backend/joanie/core/utils/webhooks.py
src/backend/joanie/tests/core/test_utils_offering.py
src/backend/joanie/tests/core/utils/test_webhooks_synchronize_course_runs.py

Enhanced logging to include more detailed information during course run synchronization.

🔊(backend) improve synchronization logging

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Changed
- Exclude archived course runs from synchronization

🔖(chore) bump to 3.0.3
