CHANGELOG.md
src/backend/joanie/settings.py
src/backend/setup.cfg

Install `django-cors-headers` to allow CORS requests from authorized domains (via environment variable) on production and from everywhere on development

✨(backend) enable cors headers

---

Dockerfile
README.md
docker-compose.yml

~Currently joanie `app` service runs on port `:8000` like richie `app` service.
Furthermore richie `nginx` and joanie `app` services are on the same network.
As richie `nginx` is a reverse proxy to `app:8000,` there is a conflict that may conduct to error if joanie starts before richie.~
➡️ Finally just changing the port does not fix the issue. I propose a solution from Richie (https://github.com/openfun/richie/pull/1351/files)
However I keep this PR opened, to update the port on which Joanie starts as it is currently the same as Marsha.

🔧(docker) run app service on port 8060

---

CHANGELOG.md
src/backend/joanie/core/api.py
src/backend/joanie/tests/test_api_address.py
src/backend/joanie/urls.py

Code related to the address api can be simplified by the use of a viewset.
Furthermore, it allows us to homogenize api route and responses.

♻️(api) use viewset for the address api

---

CHANGELOG.md
src/backend/joanie/core/api.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/serializers.py
src/backend/joanie/settings.py
src/backend/joanie/tests/test_api_address.py
src/backend/joanie/tests/test_api_course.py
src/backend/joanie/tests/test_api_enrollment.py
src/backend/joanie/tests/test_api_order.py
src/backend/joanie/tests/test_models_course.py

To avoid several requests to get the full course context and avoid extra works from the frontend, CourseSerializer is now able to retrieve authenticated user's orders and enrollments. In this way, by retrieving course details, frontend is aware of which products are already owned by the authenticated user and on which course runs the user is enrolled.

✨(api) enhance CourseSerializer

---

.circleci/config.yml
Dockerfile
env.d/development/common
src/backend/joanie/settings.py

Using a dummy key as default is the best way to end-up with a dummy key in production if we overlook this setting.
Remove the default value for `JWT_PRIVATE_SIGNING_KEY` and use Django Configuration's `SecretValue` to force explicit configuration in production.

🔒️(jwt) remove dummy key used as default for JWT signing

---

CHANGELOG.md
src/backend/joanie/core/admin.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/serializers.py
src/backend/joanie/tests/test_api_course.py
src/backend/joanie/tests/test_api_enrollment.py
src/backend/joanie/tests/test_models_course.py
src/backend/joanie/tests/test_models_course_run.py
src/backend/joanie/tests/test_models_enrollment.py
src/backend/joanie/tests/test_models_order.py

Enrollment should be allow only if course run is open. To achieve that, we decided to replicate the course run computed state implemented to Richie.
To ease review, this PR is currently based on `feature/payplug-integration` but it should be merged into `main` after #51.

Feat/course run/computed state field

---

CHANGELOG.md
src/backend/joanie/core/serializers.py
src/backend/joanie/tests/test_api_course.py
src/backend/joanie/tests/test_api_order.py

Currently, if a certificate has been generated, its related order is not serialized with his information. This gap must be filled.
---
Related issue: #75

✨(OrderSerializer) bind certificate

---

.circleci/config.yml
Dockerfile
Makefile

circleci/* images has been deprecated, we have to migrate to
the new cimg/* images.
- circleci/buildpack-deps -> cimg/base
- circleci/postgres -> cimg/postgres
- circleci/python -> cimg/python
I take this opportunity to also upgrade to python 3.10

💚(circleci) migrate to new circleci images

---

.circleci/config.yml
CHANGELOG.md
arnold.yml
src/tray/templates/services/app/_env.yml.j2
src/tray/templates/services/app/configs/__init__.py.j2
src/tray/templates/services/app/configs/settings.py.j2
src/tray/templates/services/app/deploy.yml.j2
src/tray/templates/services/app/job_db_migrate.yml.j2
src/tray/templates/services/app/secret.yml.j2
src/tray/templates/services/app/svc.yml.j2
src/tray/templates/services/nginx/configs/healthcheck.conf.j2
src/tray/templates/services/nginx/configs/joanie.conf.j2
src/tray/templates/services/nginx/deploy.yml.j2
src/tray/templates/services/nginx/ingress.yml.j2
src/tray/templates/services/nginx/secret.yml.j2
src/tray/templates/services/nginx/static-svc.yml.j2
src/tray/templates/services/nginx/svc.yml.j2
src/tray/templates/services/postgresql/deploy.yml.j2
src/tray/templates/services/postgresql/ep.yml.j2
src/tray/templates/services/postgresql/secret.yml.j2
src/tray/templates/services/postgresql/svc.yml.j2
src/tray/tray.yml
src/tray/vars/all/main.yml
src/tray/vars/settings.yml
src/tray/vars/vault/main.yml.j2

At FUN we would like to be able to deploy Joanie to Kubernetes using [Arnold](https://github.com.openfun/arnold), our tool based on Ansible to generate k8s definition files. 
Arnold supports remote trays to define a project directly in the app repository, so I propose to add this project under `src/tray`.

👷(tray) add arnold tray to deploy joanie to kubernetes

---

.circleci/config.yml

Add jobs to generate messages from codebase then upload them on our translation
management platform.

💚(i18n) add internationalization jobs

---

src/backend/joanie/core/admin.py
src/backend/joanie/core/templates/joanie/admin/translatable_change_form_with_actions.html
src/backend/joanie/tests/test_admin_course.py
src/backend/joanie/tests/test_admin_order.py
src/backend/joanie/tests/test_admin_product.py

In order to use both TranslatableAdmin with DjangoObjectActions, we have to use
a custom change form template which extends the change form provided by django
parler then add the block to append object actions.

🐛(admin) custom change form for translatable admin with actions

---

src/backend/joanie/settings.py
src/tray/templates/services/app/deploy.yml.j2
src/tray/vars/all/main.yml

This is a new setting in Django 4. It needs to be explicitly set to the origins from which we want to receive form posts.
- Add new setting for CSRF trusted origins
- Add new setting to configure CORS allowed origins
- Add environment variable in deploy manifest of Arnold tray to automatically define the CSRF trusted origins.
- Add environment variable in deploy manifest of Arnold tray to automatically define the CORS allowed origins.

🔧(tray/settings) add setting for CSRF trusted origins

---

src/tray/templates/services/app/deploy.yml.j2

Django settings have been updated with new CORS variables which use `DJANGO`
prefix but before this prefix was not use. So we have to update the tray to
rename the environment variable `CORS_ALLOWED_ORIGINS` into
`DJANGO_CORS_ALLOWED_ORIGINS`.

🔧(tray) rename CORS_ALLOWED_ORIGINS into DJANGO_CORS_ALLOWED_ORIGINS

---

src/backend/joanie/payment/tests/test_admin_invoice.py
src/backend/joanie/payment/tests/test_api_credit_card.py
src/backend/joanie/payment/tests/test_backend_base.py
src/backend/joanie/payment/tests/test_backend_payplug.py

The missing file `__init__.py`in the test folder of the payment module
blocked the check for pylint.
Adding it,  different errors appeared that needed to be fixed.
To test the class BasePaymentBackend, as it's not a class that is
supposed to be instantiated directly, a class inheriting it has been
created in the test class.
fix pylint errors

🚨(tests) fix pylint payment tests

---

src/backend/setup.cfg

Currently, when we configure static files to be managed through whitenoise, document issued through howard templates are corrupted. We [fixed this problem](https://github.com/openfun/marion/pull/117) then release a new version of marion and howard. So now we have to upgrade those dependencies into Joanie.

⬆️(deps) upgrade marion to version 0.4.0 and howard to version 0.3.0

---

env.d/development/common
src/backend/joanie/settings.py

We want to be able to configure cache durations through environment variables in order to customize then according to the deployment environment.

🔧(settings) make cache durations configurable

---

env.d/development/common

Since docker compose 2.7.0, there is an "Invalid template" error when a
environment variable which is a regex is not quoted. This is the case of
`EDX_SELECTOR_REGEX` and `EDX_COURSE_REGEX`. So we quote those two variables.

🐛(env.d) fix env compatibility issue with docker compose 2.7.0

---

src/backend/joanie/settings.py

Currently, the default language is english but at FUN, in our production / staging and preproduction environment we would like to use french as default language.

🔧(settings) use french as default language for production environment

---

src/tray/templates/services/nginx/ingress.yml.j2
src/tray/vars/all/main.yml

To use the correct ingress controller, we have to specify in the ingress
spec wich one to use with the ingressClassName parameter set to nginx

🐛(tray) specify ingress class name to use

---

Makefile
src/backend/joanie/core/serializers.py
src/backend/joanie/tests/core/test_api_course.py
src/backend/joanie/tests/core/test_api_enrollment.py

Currently, there were two serializer for Enrollment model. One used to nest enrollments and another to read/create/update enrollments from an api endpoint. This was weird. Your api should stick as much as possible to our models for clarity and sanity. That's why we remove the CourseRunEnrollmentSerializer and now use only the EnrollmentSerializer to read/write enrollments through api endpoints.

♻️(serializer) improve EnrollmentSerializer

---

Makefile

Shortcuts of the make file enable us to speed up our development. A command has been changed by mistake that does the opposite. We restore the original command.
- fix the make test-back command line

🔧(tests) fix the command make test-back

---

.circleci/config.yml

Since commit openfun/arnold@f29d31681502bd195d50cb47d207690536c5e825, Arnold requires k3d>=5. As the job `tray` is currently using k3d v4.4.8, it fails.
Thanks @rouaidakacem for the investigation :muscle:

💚(ci) fix job tray

---

CHANGELOG.md
src/backend/joanie/core/api.py
src/backend/joanie/core/factories.py
src/backend/joanie/tests/core/test_api_course_run.py
src/backend/joanie/tests/core/test_api_products.py
src/backend/joanie/urls.py

Richie must be able to retrieve course runs and products information through an API endpoint. Currently those endpoints do not exist, we have to create them.
#151

✨(api) add course runs and products endpoints

---

CHANGELOG.md
src/backend/joanie/lms_handler/urls.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_api_address.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_api_course.py
src/backend/joanie/tests/core/test_api_course_run.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_api_order.py
src/backend/joanie/tests/core/test_api_products.py
src/backend/joanie/tests/lms_handler/test_api_course_run_sync_edx.py
src/backend/joanie/tests/payment/test_api_credit_card.py
src/backend/joanie/tests/payment/test_api_payment.py
src/backend/joanie/tests/payment/test_backend_base.py
src/backend/joanie/tests/payment/test_backend_dummy_payment.py
src/backend/joanie/tests/payment/test_backend_payplug.py
src/backend/joanie/urls.py

As Roy Fielding said : "Versioning an interface is just a "polite" way to kill deployed clients.". We are polite.
Now all api routes are prefixed by `/api/v1.0/`

✨(all) version api

---

CHANGELOG.md
src/backend/joanie/core/api.py
src/backend/joanie/core/filters.py
src/backend/joanie/tests/core/test_api_enrollment.py

In order to manage standalone course runs, frontend needs to know if the authenticated user is enrolled to a given course run. To address this need we allow to filter user's enrollment through a course run id.

✨(api) allow to filter enrollments by course run id

---

.circleci/config.yml

To log in to the docker hub we use two sets of environment variables which contains the same information. We have recently to rotate our secrets and one of those environment variable has been removed that's make us aware about this duplication.

💚(circleci) homogenize docker credential environment variable

---

src/backend/joanie/core/utils.py
src/backend/joanie/settings.py

Currently, we defined through environment variables the COURSE_WEB_HOOK_URL,
COURSE_WEB_HOOK_SECRET and COURSE_WEB_HOOK_VERIFY then if COURSE_WEB_HOOK_URL
was defined, we tried to set COURSE_WEB_HOOKS settings. But unfortunately this
was not work as when this code was interpreted, COURSE_WEB_HOOK_URL was always
none. In order to fix that, we create a custom JSONValue class which takes a
JSON string as raw value then returns the python representation.
In this way we are now able to define `COURSE_WEB_HOOKS` through environment variable as following : 
```
DJANGO_COURSE_WEB_HOOKS=[{"url":"http://www.example.com", "secret": "a-secret", "verify": false}]
```

🐛(settings) use values.Value formats as JSON to set COURSE_WEB_HOOKS

---

.dockerignore
Dockerfile

Currently, mail templates are not included into the docker image for two reasons.
First, there is a mistake about the path to copy mail templates after generation.
Second mail templates are built at collectstatic stage but app files are copied again after this stage so mail files are overriden here. In order to fix that, we copy app files during collectstatic stage, generate mail templates then copy all app files from this stage.

🔧(Dockerfile) copy mail templates during

---

src/backend/joanie/settings.py
src/tray/templates/services/app/_env.yml.j2

We can consider language settings as Django settings and keep the `DJANGO_` prefix in the expected variable name that configures them, which is what the tray is doing.

🔧(settings) remove custom env variable name for language settings

---

src/backend/joanie/core/serializers.py
src/backend/joanie/tests/core/test_api_course.py
src/backend/joanie/tests/core/test_api_enrollment.py

We need this date to sort enrollments and orders coherently in the frontend (on a list view mixing both objects).
Add field to the enrollment serializer and update tests to take it into account.
I made sure in tests that the field is readonly both on create and update actions.

✨(api) add "created_on" to the enrollments API payload

---

CHANGELOG.md
README.md
src/backend/setup.cfg

- First working version serving sellable micro-credentials for multiple organizations synchronized to a remote catalog

🔖(release) bump to version 1.0.0

---

CHANGELOG.md
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/test_models_order.py

When an order is validated, if the related product has a target course with a single course run, the user is automatically enrolled to this one. In the case where there is an existing inactive enrolled for the couple user / course run, the statement to retrieve enrollment contains a syntax error.

🐛(core) fix a bug about auto enrollment on order validation

---

CHANGELOG.md
src/backend/joanie/core/models/courses.py
src/backend/joanie/tests/core/test_api_course_run.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_models_enrollment.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/core/test_signals.py

Now that Joanie is able to synchronize its course runs with Richie, we prefer that a CourseRun is not listed by default. In this way, we prevent to involuntary display a CourseRun on a catalog. Furthermore, it prevents that a course run is available for free enrollment by mistake!
Description...

🗃️(CourseRun) set `is_listed` field to False by default

---

CHANGELOG.md
src/backend/joanie/core/api.py
src/backend/joanie/core/models/certifications.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_models_certificate.py

Currently, organization logo and signature are not required to create an organization. But to create a certificate document we need this information so
when this information are missing, a ValueError is raised then an internal
server error is returned. In order to fix that we properly manage this case by
returning a 422 error.

🐛(certificate) prevent server error when certificate is unprocessable

---

CHANGELOG.md
src/backend/joanie/core/factories.py
src/backend/joanie/core/models/accounts.py
src/backend/joanie/tests/base.py
src/backend/joanie/tests/core/test_models_user.py

Currently, the jwt token used to authenticate user contains only a fullname property. As there are too much edge cases to split fullname into first and last
names, we prefer to store this property into the firstname field. It allows us
later to switch gracefully to another authentication.

✨(accounts) store user.fullname into firstname field

---

CHANGELOG.md
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_models_enrollment.py
src/backend/joanie/tests/core/test_models_order.py

We do not want a user is able to enroll on several opened course runs of the same course. Currently, we execute the check only on enrollment creation so one case was not covered by this check. Indeed if the user enrolls to a first course
run then unenroll to this course run, it is able to enroll a second course run
then re-enroll to the first one.

🐛(core) prevent to enroll on several course runs for the same course

---

CHANGELOG.md
src/backend/joanie/core/models/courses.py
src/backend/joanie/tests/core/test_models_course_run.py
src/backend/joanie/tests/core/test_models_enrollment.py

The CourseRun string representation was based on a title and the start end end date of the CourseRun instance. But start and end date fields can be null so in this case, the string representation raises a `NoneType.__format__` error. So instead to use those dates, we could use the state.

🐛(core) fix string representation of CourseRun model

---

CHANGELOG.md
src/backend/joanie/core/views.py
src/backend/joanie/payment/backends/base.py
src/backend/joanie/tests/payment/test_backend_base.py
src/mail/mjml/order_validated.mjml

When user has a full name define we should use it within our mails instead of its username.

💬(mail) use user fullname instead of username when exists

---

src/tray/vars/vault/main.yml.j2

The tray job is failing time to time with a syntax error reading the vault file. We want to remove punctuation in the generated password to not have this syntax error
Ref: https://github.com/openfun/marsha/pull/2081

🚨(tray) avoid using punctuation with password lookup

---

CHANGELOG.md
src/backend/joanie/core/api.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_api_address.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_api_order.py
src/backend/joanie/tests/payment/test_api_credit_card.py

The order and enrollment endpoints are used by the frontend to build a view mixing both objects. For this, the frontend needs to be able to customize the number of items returned by page.
This pull request proposes to activate on-demand page size on the order and enrollment endpoints. We fix the max size of the page to 100 items for security reasons.
While working on this, we realized that pagination should be activated by default on all endpoints. We set it to 20 items per page by default, not modifiable via the querystring (this can be activated on a case-by-case basis like we do here for orders and enrollments.

Allow on demand page size for orders and enrollments

---

CHANGELOG.md
src/backend/joanie/core/admin.py

On course admin change view, we decided to display related course runs with a modification link to ease content administration.

🚸(core) display course runs into admin course change view

---

Makefile

The bootstrap command does not work properly since we added the front admin install and build steps. Indeed `i18n-compile` extract now translation from front admin project. It requires formatjs to be installed so at the first bootstrap, if developper does not have installed front admin dependencies itself
the `i18n-compile` command failed.

🔨(makefile) fix bootstrap command

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/tests/core/test_api_order.py

CourseProductRelation can have several organizations. In this case, on order creation, we need to choose an organization to allocate to the order. To dispatch organization equitably, we decide to allocate the organization with least not canceled order count.

✨(core) equitably allocate organization on order

---

src/backend/joanie/settings.py

During development, we can run several django applications on local hostname. So all those applications are using the same session cookie name so they can be overridden that pretty weird. So we decide to rename joanie cookie session name in development to prevent this behaviour.
I wonder if it was not better to set the session cookie name for all environment ? 🤔

👨‍💻(settings) use specific cookie name in dev mode

---

src/backend/joanie/core/filters/client.py
src/backend/joanie/core/helpers.py
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/test_commands_generate_certificates.py
src/backend/joanie/tests/core/test_helpers.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/core/test_models_product.py

Some checks were done in the helper and others in the model which lead to unwanted behaviors when I tried adding some missing tests.
Move all checks to the method on the model which is responsible for generating the certificate and rename it to `get_or_generate_certificate` so it works the same as the `get_or_create` method on Django models.

♻️(certificates) refactor certificate generation

---

src/backend/joanie/core/api/client.py
src/backend/joanie/core/models/accounts.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/permissions.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_address.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_api_course_accesses.py
src/backend/joanie/tests/core/test_api_course_run.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_api_order.py
src/backend/joanie/tests/core/test_api_organization_accesses.py
src/backend/joanie/tests/core/test_api_organizations.py
src/backend/joanie/tests/core/test_api_products.py
src/backend/joanie/tests/core/test_models_course.py
src/backend/joanie/tests/core/test_models_course_access.py
src/backend/joanie/tests/core/test_models_organization.py
src/backend/joanie/tests/core/test_models_organization_access.py
src/backend/joanie/tests/core/test_models_user.py
src/backend/joanie/tests/payment/test_api_credit_card.py
src/backend/setup.cfg

Train thoughts: our optimization consisting in using `request.auth` instead of `request.user` was a little over-engineered as pointed out by @qbey.
We want to add abilities to the user model but should first refactor the existing `get_abilities` methods.

Refactor `get_abilities` method and add user abilities

---

CHANGELOG.md
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/test_api_course.py
src/backend/joanie/tests/core/test_models_course.py
src/backend/joanie/tests/core/test_models_product.py

Course model implements a property `state` inherits from Richie in charge of processing its state according to its course runs. As in Joanie a course can contain course runs AND products we must take these two resources in account to process course state.

✨(core) take products in account to process course state

---

src/frontend/admin/src/components/presentational/card/SimpleCard.tsx
src/frontend/admin/src/components/presentational/translatable-content/TranslatableContent.tsx

In the edit view of a multilingual resource, the language tabs are not visually separated from the edit form, so it is difficult for the user to quickly understand that he is able to change the language by clicking on these tabs.
- Add background color

💄(frontend) update TranslatableContent UI

---

src/frontend/admin/src/components/presentational/link/CustomLink.tsx
src/frontend/admin/src/components/templates/certificates-definitions/list/CertificatesDefintionsList.tsx
src/frontend/admin/src/components/templates/courses-runs/list/CourseRunsListColumns.tsx
src/frontend/admin/src/components/templates/courses/list/CoursesList.tsx
src/frontend/admin/src/components/templates/organizations/list/OrganizationsList.tsx
src/frontend/admin/src/translations/common/commonTranslations.ts

Currently to edit a ressource, the user must click on the three vertical dots icon then click on "edit" link that is weird.
Make the main attribute of a resource clickable to be redirected to the edit form.

✨(frontend) allow click to edit on main ressource attribute

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_course.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/core/test_api_products.py
src/backend/joanie/urls.py

API consumer needs a route to retrieve all products sold on courses for which authenticated user has accesses. After some thoughts, it appears the simpler way to get this information is requesting directly course product relations.
Furthermore, at term, we could fully replace the product endpoint by this new endpoint.

✨(backend) add api endpoint to list course product relations

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/tests/core/test_api_course_run.py
src/backend/joanie/urls.py

API consumer needs to list course runs related to a specific course. In order to do that, we create a new nested course api route `/courses/:course-id/course-runs`.

✨(core) add nested course api endpoint to list course runs

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_course.py

In some case, api consumer needs to retrieve courses which have listed course runs. So we add a course filter to allow to filter courses according to whether they have listed course runs or not.

✨(core) add `has_listed_course_runs` filter to course resource

---

src/backend/joanie/core/api/client.py
src/backend/joanie/tests/core/test_api_course_run.py

It appears that the endpoint `/courses/<course_id>/course_runs/` was not working as expected. So we fix the behavior and consolidate tests that were too weirds.

🚑(backend) fix course runs api endoint with nested course

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/management/commands/loaddatafake.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_course_product_relations.py

[#1997](https://github.com/openfun/richie/pull/1997) is ready to merge. Should be done after the merge of this branch.
In order to ease development, the demo data should generated listed course runs.
Furthermore, API consumer needs to retrieve a single course product relation through its id.

🧑‍💻(backend) Adapt course endpoint for dashboad teacher

---

CHANGELOG.md
src/backend/joanie/core/api/admin.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_course_access.py
src/backend/joanie/tests/core/test_api_admin_organization_access.py
src/backend/joanie/urls.py

Backoffice need to create / update / delete course accesses to create api endpoints to allow that.
- [POST] `/api/v1.0/admin/courses/<course_id:uuid>/accesses/`
- [OPTIONS] `/api/v1.0/admin/courses/<course_id:uuid>/accesses/`
- [PUT] `/api/v1.0/admin/courses/<course_id:uuid>/accesses/<course_access_id:uuid>/`
- [PATCH] `/api/v1.0/admin/courses/<course_id:uuid>/accesses/<course_access_id:uuid>/`
- [DELETE] `/api/v1.0/admin/courses/<course_id:uuid>/accesses/<course_access_id:uuid>/`
- [POST] `/api/v1.0/admin/organizations/<organization_id:uuid>/accesses/`
- [OPTIONS] `/api/v1.0/admin/organizations/<organization_id:uuid>/accesses/`
- [PUT] `/api/v1.0/admin/organizations/<organization_id:uuid>/accesses/<organization_access_id:uuid>/`
- [PATCH] …

✨(api/admin) add endpoint to create/udpate/delete course accesses

---

src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_course.py

The filter `has_listed_course_runs` return non distinct course. So when filtering course whose have listed course runs it returns the resource as many as it has listed course runs.

🐛(api/client) fix has_listed_course_runs course filter

---

src/backend/joanie/core/admin.py

We recently improve admin by adding search fields to some models. Some fields declared as searchable are translated fields and their name were not prefixed with `translation__` so for those views, search failed.

🐛(backend) fix admin search fields

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_enrollment.py

We want to be able to sell certificate products from the dashboard ie to students already enrolled to a course. 
Add a `products` field to the enrollment API endpoint serializer.
I tried to optimize queries a little by prefetching product relations for an enrollment in the API viewset. The serializer uses the prefetched products if available from the viewset and otherwise does the query itself.
Related to https://github.com/openfun/joanie/issues/316

✨(api) add related certificate products to enrollment API endpoint

---

.circleci/config.yml
CHANGELOG.md
env.d/development/common
src/backend/joanie/core/api/__init__.py
src/backend/joanie/core/api/client.py
src/backend/joanie/core/enums.py
src/backend/joanie/core/models/products.py
src/backend/joanie/payment/backends/base.py
src/backend/joanie/payment/models.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_api_order.py
src/backend/joanie/tests/core/test_commands_generate_certificates.py
src/backend/joanie/tests/core/test_helpers.py
src/backend/joanie/tests/core/test_models_enrollment.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/core/test_models_order_get_or_generate_certificate_for_credential_product.py
src/backend/joanie/tests/payment/test_backend_base.py
src/backend/joanie/tests/payment/test_backend_dummy_payment.py
src/backend/joanie/tests/payment/test_backend_payplug.py

resolve #363
Add states and transitions to the Order FSM
Refactor the Order's model FSM and allow to create orders without billing_address.
An order (for a non free product) created without billing_address must be in draft state
Description...

✨(backend) Refactor order FSM

---

CHANGELOG.md
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_order.py

We are now selling several product types (credential, certificate). Frontend now needs to be able to filter user's order by product type.

✨(core) allow to filter order by product type

---

CHANGELOG.md
src/backend/joanie/core/utils/webhooks.py
src/backend/joanie/demo/defaults.py
src/backend/joanie/demo/management/commands/create_dev_demo.py
src/backend/joanie/tests/demo/test_commands_create_dev_demo.py

In order to do the incoming feature to buy a product certificate from enrollment, we need to have some data in our demo-dev script.
This script can generate some errors when executed on step "create 5 fake PRODUCT_CREDENTIAL"
I got some fails with error: 
```
Max retries exceeded with url: /api/v1.0/course-runs-sync/ (Caused by ResponseError('too many 500 error responses'))
```

🔨(backend) PRODUCT_CERTIFICATE in demo-dev

---

CHANGELOG.md
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_products.py

The admin product serializer now displays the whole relation with target courses
The admin product serializer lacked some data regarding `ProductTargetCourseRelation`

✨(backend) change data returned by admin product serializer

---

src/backend/joanie/core/api/admin.py
src/backend/joanie/tests/core/test_api_admin_products.py

Creation of a target_course without course_run should not crash when course_run is given as an empty string

🐛(backend) allow target course creation without course run

---

src/backend/joanie/core/api/admin.py
src/backend/joanie/tests/core/test_api_admin_course_runs.py

Removed most warnings from django. Some could not be removed as they are originating from libraries

🚨(backend) remove django warnings

---

src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_products.py

We need to allow users to update products with empty instructions, and allow instructions to have trailing newline and whitespace
Description...

✨(api) product serializer accepts empty instructions

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_enrollment.py

Products are being sold on enrollments. If the product is already subject to an order on an enrollment, the "purchase" button should not be shown. We need to include the complete information about orders related to an enrollment so the frontend is able to decide what should be displayed.

✨(api) add list of related orders to enrollments API payload

---

CHANGELOG.md
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_models_enrollment.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/core/test_models_order_enroll_user_to_course_run.py

When a course has several course runs, some of them being open and others being closed, the query does not see that only one course run is open and fails to enroll the user automatically. 
The case of a product with target courses limited to specific course runs is also not taken into account.
I proposed a refactoring of the query (not so trivial! :sweat_smile:) and added tests for all the overlooked use cases I could think of.
Fixes https://github.com/openfun/joanie/issues/389

🐛(models) fix auto enrollment with closed and specific course runs

---

src/backend/joanie/core/admin.py

Currently, it is not possible to access to contract definition django admin view . Indeed the related model Admin class currently inherits from TranslatableAdmin
but this model is not translatable so an error is raised.

🐛(backend) fix contract definition admin view

---

Makefile

The help did not work as expected; indeed command names were not displayed.
Then the command `test` was not working anymore since we updated the
`test-back` command. Furthermore, we recently add a command to run admin
frontend tests. So the `test` command should run both `test-back` and
`admin-test` commands now.

🔧(Makefile) fix help command

---

src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_products.py

The product model accepts blank values for description and instructions but the  admin api endpoint does not allow to create this resource with blank values for those fields. So we update serializer to fix this point.

✨(api) allow to send blank description/instructions field

---

CHANGELOG.md
src/backend/joanie/lms_handler/api.py
src/backend/joanie/tests/lms_handler/test_api_course_run_sync_edx.py

We need to synchronize the complete catalog from a remote LMS. 
Since we trust this LMS, we can create missing courses automatically with the information included in the course run synchronization payload. If the title information is not in the payload, we default to using the code as a first title that can later be changed in joanie.

✨(lms) create missing courses automatically on course run sync

---

CHANGELOG.md
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_order.py

In PR https://github.com/openfun/joanie/pull/425 @rlecellier made the following request:
> I'll need to have a filter on (enrollment/productId) in the OrderViewset. This is used when we display the payment button, mostly to be sure that we disable the button when an order is created (avoid double click) 
Allow filtering orders related to a specific enrollment (filtering on a specific product is already there).
While working on this, it occured to me that the frontend needed to filter all orders except the ones that are `canceled`. The frontend does this by listing in the querystring all the states other than the one it wants to exclude. This is an anti-pattern prone to future bugs if we later add a new state. Since the intention is to exclude the `canceled` orders, our filters should …

Add filter on order endpoint

---

CHANGELOG.md
src/backend/joanie/core/api/admin.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_admin_order_group.py
src/backend/joanie/tests/core/test_api_admin_products.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/urls.py

Add routes to create and edit order groups on the admin api
resolves part of issue #408

✨(backend) add admin route for OrderGroups

---

CHANGELOG.md
src/backend/setup.cfg

Django 4.2 supports psycopg 3, and will remove support for version 2 in the future.

⬆️(backend) update psycopg to version 3

---

src/backend/joanie/core/factories.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_course.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/core/test_api_courses_contract.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_api_order.py
src/backend/joanie/tests/core/test_api_organizations.py
src/backend/joanie/tests/core/test_api_organizations_contract.py
src/backend/joanie/tests/core/test_api_organizations_course_product_relations.py
src/backend/joanie/tests/core/test_api_organizations_courses.py

Our tests are really long to run (10 min locally), which causes a huge dev worflow problem.
It appears that we have many db request made for each of our data factories.
Also, default default password hasher is quite long to execute.
It appears that removing it doesn't change the expected output of the tests, so I purely deleted them.

✅(backend) decrease testing time

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_courses_contract.py
src/backend/joanie/tests/core/test_api_organizations_contract.py

NestedOrderSerializer needs to return enrollment, and to have more descriptive attributes.

Update nested order serializer

---

src/frontend/admin/mocks/handlers/organizations/index.ts
src/frontend/admin/src/components/presentational/table/TableComponent.tsx
src/frontend/admin/src/components/presentational/table/usePaginatedTableResource.ts
src/frontend/admin/src/components/presentational/table/useTableResourcePagination.spec.tsx
src/frontend/admin/src/components/presentational/table/useTableResourcePagination.ts
src/frontend/admin/src/components/templates/certificates-definitions/list/CertificatesDefinitionsList.tsx
src/frontend/admin/src/components/templates/courses-runs/list/CoursesRunsList.tsx
src/frontend/admin/src/components/templates/courses/list/CoursesList.tsx
src/frontend/admin/src/components/templates/organizations/list/OrganizationsList.tsx
src/frontend/admin/src/components/templates/products/list/ProductsList.tsx
src/frontend/admin/src/hooks/useResources/index.tsx
src/frontend/admin/src/utils/constants.ts

Currently, lists are not paginated, although by default they are on the backend  side. To resolve this issue, we added a hook that simplifies resource paging management.

✨(frontend) paginate resources lists

---

src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_api_order.py

A test using EnrollmentLightSerializer was flaky because of a random course run state which caused some date to be randomly null, and so fails the test.
Conditionally test for dates.

✅(backend) fix flaky test

---

src/backend/joanie/core/admin.py

Currently this is not possible to update contract_definition from an existing product. So we add the missing `contract_definition` to the ProductAdmin view

✨(backend/admin) add contract_definition field into product change view

---

src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_api_order.py

A test using EnrollmentLightSerializer was flaky because of a random course run state which caused some date to be randomly null, and so fails the test.
Conditionally test for dates.

Fix flacky backend test

---

CHANGELOG.md
src/backend/joanie/core/models/courses.py
src/backend/joanie/tests/core/test_models_enrollment.py

Currently, the `full_clean` method check if the related course run of an enrollment is opened before saving any change on the enrollment.
This check aims to forbid that someone enrolls to a closed course runs but currently it blocks any modifications on this resource that is a bug ...

🐛(backend) allow to unroll to closed course run

---

CHANGELOG.md
Makefile
docker-compose.yml
src/backend/joanie/celery_app.py
src/backend/joanie/settings.py
src/backend/pyproject.toml
src/tray/templates/services/app/_deploy_base.yml.j2
src/tray/templates/services/app/deploy_app.yml.j2
src/tray/templates/services/app/deploy_celery.yml.j2
src/tray/vars/all/main.yml

We want to add long task management in joanie. For this, we chose to use
the celery application with redis. We need a redis server running in our
docker-compose configuration and then create a celery app launch by a
celery server also added in docker-compose

Install and configure celery with redis

---

.circleci/config.yml
Makefile
src/backend/pyproject.toml

Running tests in parralel would reduce testing time.
Use pytest-xdist

✅(backend) run tests in parallel

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/payment/backends/dummy.py
src/backend/joanie/payment/backends/payplug/__init__.py
src/backend/joanie/tests/core/test_api_course.py
src/backend/joanie/tests/core/test_api_course_accesses.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/core/test_api_course_run.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_api_order.py
src/backend/joanie/tests/core/test_api_organization_accesses.py
src/backend/joanie/tests/core/test_api_organizations_course_product_relations.py
src/backend/joanie/tests/core/test_serializers_course_access.py
src/backend/joanie/tests/core/test_serializers_organization_access.py
src/backend/joanie/tests/payment/test_backend_dummy_payment.py
src/backend/joanie/tests/payment/test_backend_payplug.py

Some serializer attribute name are misleading.
ie: if product attribute contains only a product id, it should be renamed to product_id
Rename serializers attributes to be more descriptive:

Update serializers attributes

---

CHANGELOG.md
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_api_order.py

Some query attributes are misleading ie: product was awaiting for a product_id.
Updated filters:
- OrderViewSetFilter
- ProductViewSetFilter
- EnrollmentViewSetFilter

💥(backend) rename client query attribute filters

---

CHANGELOG.md
src/backend/joanie/core/api/admin.py
src/backend/joanie/core/factories.py
src/backend/joanie/core/filters/admin.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/api/admin/course-product-relations/test_create.py
src/backend/joanie/tests/core/api/admin/course-product-relations/test_delete.py
src/backend/joanie/tests/core/api/admin/course-product-relations/test_list.py
src/backend/joanie/tests/core/api/admin/course-product-relations/test_retrieve.py
src/backend/joanie/tests/core/api/admin/course-product-relations/test_update.py
src/backend/joanie/tests/core/test_api_admin_contract_definitions.py
src/backend/joanie/tests/core/test_api_admin_courses.py
src/backend/joanie/tests/core/test_api_admin_order_group.py
src/backend/joanie/tests/core/test_api_admin_products.py
src/backend/joanie/tests/core/test_models_course_product_relation.py
src/backend/joanie/tests/core/test_models_order_group.py
src/backend/joanie/urls.py
src/backend/pyproject.toml
src/frontend/admin/package.json

We need to bind course_runs to the AdminCourseSerializer.
Add a CRUD to create a courseProductRelation directly to a course
Add a can_edit property to CourseProductRelation and OrderGroup models which are false if a related order exists.
This is the backend part needed for #460 
Description...
- post /api/v1.0/admin/course-product-relations/
- get /api/v1.0/admin/course-product-relations/
- get /api/v1.0/admin/course-product-relations/<course_product_relation_id>
- put /api/v1.0/admin/course-product-relations/<course_product_relation_id>
- delete /api/v1.0/admin/course-product-relations/<course_product_relation_id>

✨(backend) update admin API

---

.circleci/config.yml
src/backend/joanie/settings.py
src/tray/vars/all/main.yml

We recently installed a dev dependencies installed only in Development
environment. That's break the tray, as this one is using a joanie docker image
build with a production target. As dev dependencies are not installed, some job
fails with a ModuleNotFoundError. So in order to fix that, we decide to use
Staging django enviromnent as default value instead of Development.

💚(ci) fix tray job

---

CHANGELOG.md
src/backend/joanie/core/management/commands/synchronize_course_runs.py
src/backend/joanie/tests/core/test_commands_synchronize_course_runs.py

In some case, we could need to manually trigger course run or product synchronization. We are now able to do that through this management command. Furthermore, in the hypothesis, later we would want to remove automatic synchronization logic based on signals, we were able to trigger synchronization by invoking this management command.

✨(backend) add synchronize_course_runs management command

---

src/backend/joanie/core/api/client.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/core/tasks.py
src/backend/joanie/core/utils/contract.py
src/backend/joanie/settings.py
src/backend/joanie/signature/management/commands/generate_zip_archive_of_contracts.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_commands_generate_zip_archive_of_contracts.py
src/backend/joanie/tests/swagger/swagger.json

University representatives will be able to fetch their signed contracts in a ZIP archive through two actions.
The viewset to **generate the ZIP archive** (POST) requires : 
- a user that has access to a specific organization (required)
- an organization UUID
- OR a course product relation UUID
The other viewset will handle in **returning the ZIP archive** (GET) once it has been generated
in the response. It requires : 
- requesting user is the same that the one who requested the ZIP archive. It must have access to a specific organization.
- a valid ZIP UUID in order to build the ZIP archive name and seek for it in storages.

✨(backend) Route to create and get zip archive

---

src/backend/joanie/tests/__init__.py
src/backend/joanie/tests/core/test_api_admin_courses.py
src/backend/joanie/tests/core/test_api_certificate.py

We are repeating date formating in many tests.
As it is too much to manage them all in only one PR, a helper has been used in two of them.
Other tests may be cleaned as we work on them.

🧑‍💻(backend) add a date format helper

---

src/backend/joanie/core/factories.py
src/backend/joanie/tests/core/api/order/test_submit_for_signature.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/core/test_api_courses_contract.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_api_organizations_contract.py
src/backend/joanie/tests/core/test_models_contract.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/core/test_utils_contract.py
src/backend/joanie/tests/signature/backends/lex_persona/test_handle_notification.py
src/backend/joanie/tests/signature/test_backend_signature_base.py
src/backend/joanie/tests/signature/test_commands_generate_zip_archive_of_contracts.py

Currently, the ProductFactory always create a ContractDefinition. This is relation is not mandatory, so we should not create one on each Product but only when it is expected.

🔥(backend) does not create contract definition for all product

---

CHANGELOG.md
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/models/products.py
src/backend/joanie/signature/backends/base.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_models_enrollment.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/signature/test_backend_signature_base.py

We want to forbid enrollment to not listed course run until a user has a validated order and has signed the contract link to the order if there is one. Currently, we do not check the contract signature state. 
Furthermore, currently, if a target course has only one course run and this one is opened for enrollment we automatically enroll the user on order validation. We have to update this logic according to if there is a contract to sign or not : 
1. If there is no contract, we should keep the current behaviour
2. If there is contract to sign, we should enroll the user only after it signs it.

✨(backend) prevent to enroll on course runs if signature is missing

---

src/tray/vars/all/main.yml

The command starting the celery app contains a leading double quote and the container was failing to start because of that.

💚(tray) fix command starting celery app

---

src/backend/joanie/core/admin.py
src/backend/joanie/core/api/client.py
src/backend/joanie/core/exceptions.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/tests/core/test_api_organizations.py
src/backend/joanie/tests/core/test_models_organization.py
src/backend/joanie/tests/swagger/swagger.json

An organization owner should be able to sign multiple contracts once they are signed by a student.
Add an API endpoint to generate a signature link for all contracts to sign.

Organization multiple contracts signature

---

src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_api_admin_courses.py
src/backend/joanie/tests/core/test_api_admin_organizations.py
src/backend/joanie/tests/core/test_api_admin_products.py
src/backend/joanie/tests/core/test_api_organizations.py

We previously declare easy thumbnail aliases and for all of them, we set crop property to "smart". It appears this configuration is weird as the asset can be truncated to fit the size defined. To prevent that, a good workaround seems to set "crop" argument to "scale"

🩹(backend) fix crop setting of easy thumbnail aliases

---

CHANGELOG.md
src/backend/joanie/core/enums.py
src/backend/joanie/core/factories.py
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_courses_contract.py
src/backend/joanie/tests/core/test_api_organizations_contract.py
src/backend/joanie/tests/swagger/swagger.json

Previously, we allow to filter contract by signed state. Since we introduce the
double signature logic (student and organization), this filter is no more
relevant and confusing. Indeed, it returns contract at least signed by student
but it could let understand that it should return contracts signed by both
student and organization. We have to replace this filter by something more relevant.
Furthermore we need to be able to retrieve Contract to a specific organization or course
product relation. That's why we added three new filters on Contract API Viewset:
organization_id, course_id and product_id.

✨(backend) improve contract filters

---

src/backend/joanie/core/api/client.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/tests/core/test_api_organizations.py
src/backend/joanie/tests/core/test_models_organization.py

`contracts_signature_link` is in charge to generate an invitation link to sign all contracts which are pending for the related organization signature. For API consumers, it is interesting to retrieve the list of all contract ids implies in the signature process. In this way, API Consumer could be able to retrieve related contracts to ensure that they have been updated properly once the signature has been done. (That's why we added a filter by `id` into Contract ViewSets in PR #525)

✨(backend) return contract_ids into contracts_signature_link response

---

src/backend/joanie/core/models/courses.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_create.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_list.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_retrieve.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_update.py
src/backend/joanie/tests/core/test_api_admin_course_runs.py
src/backend/joanie/tests/core/test_api_admin_courses.py
src/backend/joanie/tests/core/test_api_admin_products.py
src/backend/joanie/tests/core/test_models_course_product_relation.py
src/backend/joanie/tests/core/test_models_course_run.py
src/backend/joanie/tests/swagger/admin-swagger.json

Back office needs to retrieve uri of CourseRun and CourseProductRelations in order to improve UX about those models.

♻️(backend) add uri property to CourseRun et CPR models

---

CHANGELOG.md
env.d/development/common.dist
src/backend/joanie/core/api/remote_endpoints.py
src/backend/joanie/core/permissions.py
src/backend/joanie/core/utils/course_run.py
src/backend/joanie/remote_endpoints_urls.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/api/remote_endpoints/course_run/test_course_run.py
src/backend/joanie/tests/core/test_utils_course_run.py
src/backend/joanie/urls.py

Implement a secure way to communicate between Joanie and other services (other apps) if they want to retrieve
some data through an endpoint.
Add new endpoint that returns the awaited data needed by JENNY FunERP about course run metrics on : enrollments and unclocking access to obtain a certificate.
First, we will implement a new setting that will store every valid Token (`AUTHORIZED_API_TOKENS`). 
The token must be declared into the settings of the other service in order to use it in the headers of their request. Without a valid token that is set into `AUTHORIZED_API_TOKENS`, we reject them immediately. If that first step is validated, they should also provide an existing `resource_link` of a `course_run` in order to get their values in return.
The new endpoint for remote services will …

✨ (backend) - remote endpoint API Joanie for other services (token security and endpoint)

---

Makefile

In order to work properly, make command to create an env variable from a template file should be named with the exact path of the related file otherwise an Error 1 is returned.

🔧(Makefile) fix command name to create frontend admin .env file

---

src/backend/joanie/demo/management/commands/generate_jwt_tokens.py

The command "generate_jwt_tokens" is really useful but, it could be improved to ease the work of frontend developers on Richie. Indeed, for developer, richie allows to use a fake authentication interface which just get value from an object containing a keypair username/jwt_tokens. So we update the command to log
in output this object, in this way, developer has just to copy/paste it to have
fresh users.
```
Copy the following into your dummy.ts file in Richie:
{
"user3": "eyJhb**.eyJ0b2tlbl90**.Dpy4bjPpf**",
"user4": "eyJhb**.eyJ0b2tlbl90**.Dpy4bjPpf**",
"student_user": "eyJhb**.eyJ0b2tlbl90**.Dpy4bjPpf**",
"test": "eyJhb**.eyJ0b2tlbl90**.Dpy4bjPpf**",
"admin": "eyJhb**.eyJ0b2tlbl90**.Dpy4bjPpf**",
"user0": "eyJhb**.eyJ0b2tlbl90**.Dpy4bjPpf**",
"user1": …
```

👨‍💻(backend) improve dx of generate_jwt_tokens command

---

src/backend/joanie/core/api/client.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_courses_contract.py
src/backend/joanie/tests/core/test_api_organizations.py
src/backend/joanie/tests/core/test_api_organizations_contract.py

Currently, the bulk data signature endpoint embeds also contract relying on canceled orders that is weird. We fix that and to keep api consistent we also filter out contracts which are no relying on validated orders on contract endpoints.

🐛(backend) exclude not validated order contract from bulk signature

---

.circleci/config.yml

In the hub-admin job we were not testing the good tagged image. We were testing fundocker/joanie instead of fundocker/joanie-admin

🐛(circle) fix hub-admin job

---

src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_create.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_list.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_retrieve.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_update.py
src/backend/joanie/tests/core/test_api_admin_products.py
src/backend/joanie/tests/swagger/admin-swagger.json

Admin api consumer should be able to set a contract definition to a product, currently ProductSerializer does not allow that. So we add contract definition to read and write Product serializers.

✨(backend) add contract_definition to product admin api

---

CHANGELOG.md
docs/media.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/models/certifications.py
src/backend/joanie/core/templates/issuers/contract_definition.html
src/backend/joanie/core/templates/issuers/invoice.css
src/backend/joanie/core/templates/issuers/invoice.html
src/backend/joanie/payment/models.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_utils_issuers_invoice_generate_document.py
src/backend/joanie/tests/payment/test_models_invoice.py
src/backend/joanie/urls.py
src/backend/pyproject.toml

Since we added contract models, we have all the stuff to generate PDF document without Marion and Howard. So in order to ease maintainability and remove dependencies, we internalize **invoice template**. 
This is the last migration step, once this will be done we will be able to remove marion/howard dependencies.

Feat/Invoice template and remove Howard/Marion dependencies

---

src/frontend/admin/src/components/presentational/dnd/DndDefaultRow.tsx
src/frontend/admin/src/components/presentational/list/DefaultRow.tsx
src/frontend/admin/src/components/templates/courses/form/product-relation/CourseProductRelationForm.tsx
src/frontend/admin/src/components/templates/courses/form/sections/product-relation/CourseProductRelationRow.tsx
src/frontend/admin/src/components/templates/products/form/ProductForm.tsx
src/frontend/admin/src/components/templates/products/form/sections/course-product-relations/ProductFormCourseProductRelations.tsx
src/frontend/admin/src/pages/admin/products/[id]/edit.tsx
src/frontend/admin/src/services/api/models/Product.ts
src/frontend/admin/src/services/factories/product/index.ts
src/frontend/admin/src/services/http/HttpService.ts
src/frontend/admin/src/tests/product/product.test.e2e.ts

Currently, we cannot see the courses to which the products are attached. So we
add a list below the form

✨(frontend) add course product relations 

---

src/backend/joanie/core/api/client.py
src/backend/joanie/tests/core/test_api_contract.py

The zip-archive route now accepts the OPTIONS verb. Whe this verb is used, the route returns a 204 if the zip exists. 404 otherwise. The behaviour for the GET is not changed.
Partially implementing feature in issue #546

✨(back) allow OPTIONS verb on zip-archive route testing zip creation

---

src/frontend/admin/src/components/presentational/hook-form/RHFAutocomplete.tsx
src/frontend/admin/src/components/templates/contract-definition/inputs/ContractDefinitionSearch.tsx
src/frontend/admin/src/components/templates/contract-definition/modals/CreateOrEditContractDefinitionModal.tsx
src/frontend/admin/src/components/templates/products/form/sections/main/ProductFormMain.tsx
src/frontend/admin/src/components/templates/products/form/translations.ts
src/frontend/admin/src/services/api/models/Product.ts
src/frontend/admin/src/services/factories/product/index.ts
src/frontend/admin/src/tests/product/ProductTestScenario.ts
src/frontend/admin/src/tests/product/product.test.e2e.ts

Today, we cannot link a product to a contract definition. We therefore add this possibility in the form

✨(frontend) add contract definition product form

---

src/backend/joanie/core/serializers/admin.py
src/backend/joanie/signature/backends/dummy.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/signature/test_backend_signature_dummy.py
src/backend/joanie/tests/swagger/admin-swagger.json

We recently add organization contract signature but some logic is missing.
Indeed, the AdminContractSerializer has not been updated to embedded the `organization_signed_on` field.
Then, the `DummySignatureBackend` was not up to date so it was not working to sign contract from an organization.

✨(backend) add missing logic related to organization contract signature

---

src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/swagger/admin-swagger.json

In backoffice, we would like to list order invoicing detail. Currently the invoice serializer does not embedded children field that is weird as if an order
has been refunded, a credit note will be linked to the order main_invoice but
we were not able to display this information in backoffice.

✨(backend) bind children invoices to AdminInvoiceSerializer

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/models/certifications.py
src/backend/joanie/core/models/contracts.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/utils/contract_definition.py
src/backend/joanie/core/utils/issuers.py
src/backend/joanie/core/views.py
src/backend/joanie/signature/backends/dummy.py
src/backend/joanie/tests/core/test_models_certificate.py
src/backend/joanie/tests/core/test_models_contract.py
src/backend/joanie/tests/core/test_utils_contract_definition_generate_document_context.py
src/backend/joanie/tests/core/test_utils_issuers_certificate_and_degree_generate_document.py
src/backend/joanie/tests/core/test_utils_issuers_contract_definition_generate_document.py
src/backend/joanie/tests/core/test_utils_issuers_invoice_generate_document.py
src/backend/joanie/urls.py

For consistency in the code, we would like to use the **generic method** in Issuers (`joanie.core.issuers`) `generate_document(name=name, context=context)` instead of the methods within the models `Certificate` and `Contract Definition` : `generate_document()` for PDF bytes format document.
**Refactor/replace generate document in models by issuer**
Take away from models `Certificate` and `Contract Definition` the method : `def generate_document()` with the generic method in issuers (`joanie.core.issuers`) .
You will need to update every tests, and also where the model method is called.
**Contract Definition**
**Certificate/Degree**
**Debug views to preview templates in Joanie (Bonus)**

:recycle:Replace generate_document in models Certificate and Contract Definition by the generic method in Issuers generate_document instead

---

Dockerfile
src/backend/pyproject.toml

The latest used version of Weasyprint did not use Cairo anymore.
The installation documentation of Weasyprint forgot to mention "pango1.0-tools" as a
dependency.

Fix dependencies

---

CHANGELOG.md
src/tray/templates/services/app/_deploy_base.yml.j2

In the joanie app tray, the configs/settings.py.j2 file exists. This file is here to allow to override the settings class in arnold. But to exploit this feature, the Deployment must mount the associated ConfigMap in the the joanie container. This commit add this.

✨(tray) allow to override settings

---

CHANGELOG.md
src/backend/joanie/core/storages.py
src/backend/joanie/settings.py

We want to use a S3 storage with easy_thumbnail. We are already using it for the default storage, we just want to redefined the location. Easy_thumbnail lib is still not using the storages settings introduced in django 4 so we have to create a dedicated class extending boto3 class. Pylint is warning us to override some abstract method, but this is not our job to do that, it should be handle by boto3.

✨(back) dedicated storage for easy_thumbnail using boto3

---

CHANGELOG.md
src/backend/joanie/settings.py
src/tray/templates/services/app/_deploy_base.yml.j2

The admin backoffice must send CSRF Token provided by Joanie django app to RUD resources. The admin backoffice must be served on the sudmain of the Joanie django app but by default the CSRF Cookie is only accessible on the same domain.
We must be able to configure the django setting `CSRF_COOKIE_DOMAIN` to share
this cookie on all subdomains to make it work.

🔧(backend) allow to configure CSRF_COOKIE_DOMAIN from env vars

---

src/tray/templates/services/app/_deploy_base.yml.j2

The protocol was missing to the `JOANIE_BACKOFFICE_BASE_URL` environment variable

🔧(tray) fix `JOANIE_BACKOFFICE_BASE_URL` env value

---

src/backend/joanie/signature/backends/lex_persona.py
src/backend/joanie/tests/signature/backends/lex_persona/test_submit_for_signature.py

Our user does not have lastname fulfilled, indeed, on our authentication platform, there is only a full name that we store into the first name field. To submit a contract to organization signature, we were using the `user.last_name` but as this field was blank, Lex Persona returned an error.

🩹(backend) do not use user.last_name to create org signatory step

---

src/backend/joanie/core/api/client.py
src/backend/joanie/tests/core/test_api_course_product_relations.py

On the course product relation, a distinct call was missing so when the relation
was linked to several organizations, a 500 error was raised due to the fact
that the get request matched multiple relations.
https://gip-fun-mooc.sentry.io/issues/4889287908/?environment=preproduction&project=6599941&query=is:unresolved&statsPeriod=30d&stream_index=9

🚑(backend) fix multiple get results in api client

---

src/tray/templates/services/admin/deploy.yml.j2

In the admin deployment, the imagePullPolicy is not set. We must use the Always policy to pull the last image with the same tag.

🔧(tray) set imagePullPolicy in admin deployment

---

docker/files/admin/etc/nginx/conf.d/default.conf

Currently, on the back office, if a user tries to go directly on a resource page, it gets a 404 error. As we made a static export of our next application, we can't take apart of the fallback option from the getStaticPaths method. In order to prevent to have to build our next application to run through a node server, we decide to simply add a nginx location rule to try to find the right html file for dynamic routes containing an id parameter.
e.g : With this fix, the route `/admin/courses/123/edit` will match the file `/admin/courses/[id]/edit.html`

🔧(admin) update admin nginx conf to match files for dynamic routes

---

CHANGELOG.md
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_courses_contract.py
src/backend/joanie/tests/core/test_api_organizations_contract.py
src/backend/joanie/tests/swagger/swagger.json

Our frontend consumer needs to be able to filter contracts through a course product relation id instead of a couple product / course id.
Close #575

✨(backend) filter contract through a course product relation id

---

src/backend/joanie/core/factories.py

Some tests can fail randomly due to a difference in the order of languages dict of a course run resource. In those tests, we are using `assertCountEqual` method
to compare resource with expected one regardless list order.

✅(backend) fix flaky test with course run languages order

---

CHANGELOG.md
src/backend/joanie/client_urls.py
src/backend/joanie/core/api/client.py
src/backend/joanie/core/filters/client.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_courses_order.py
src/backend/joanie/tests/swagger/swagger.json

Get the list of validated orders from a Course.
We need to able to list all the learner that have a validated order for a given course.
This will allow the authenticated user to get this list and he will be able to filter the list by different query parameters which are 
`product_id`, `organization_id`, or a `course_product_relation_id`.

✨(backend) list users with validated orders for a course 

---

src/backend/joanie/core/api/client.py
src/backend/joanie/core/pagination.py
src/backend/joanie/settings.py
src/backend/joanie/tests/swagger/admin-swagger.json
src/backend/joanie/tests/swagger/swagger.json

The setting DEFAULT_PAGINATION_CLASS was using a pagination class defined in rest_framework but we are using an other one in our viewsets. To be coherent and to avoid to define it every time, we choose to change the default class and remove the pagination property in evey viewset.

♻️(back) change default rest framework pagination class

---

src/backend/joanie/core/factories.py
src/backend/joanie/tests/core/test_models_contract.py

In dev environment we should always use dummy backends.
Here our ContractFactory wasn't providing the needed information to
trigger usage of contract's archive generation dummy backend.

🧑‍💻(frontend) use dummy backend in ContractFactory

---

src/backend/joanie/lms_handler/backends/moodle.py
src/backend/joanie/tests/lms_handler/test_backend_moodle.py

The moodle webservice to create users return a list of new users as response. Our current implementation access the response as a dict so an AttributeError is raised when the backend tries to create a user on the fly during an enrollment.

🐛(backend) fix backend moodle create_user

---

src/backend/joanie/client_urls.py
src/backend/joanie/tests/core/test_models_course_product_relation.py
src/backend/joanie/tests/swagger/swagger.json

Course and Organizations api uri are declared to match either code or id field. But the pattern used to match those fields does not match code containing letter
and underscore chars. So we fix the pattern to match it.
https://gip-fun-mooc.sentry.io/issues/4935081024/?environment=preproduction&project=6599941&query=is:unresolved&statsPeriod=30d&stream_index=6

🐛(backend) fix course & organization uri patterns

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/swagger/swagger.json

API consumer needs to filter course product relation by product type. So we add two filter to filter out either by product type or by excluded product type.
https://github.com/openfun/richie/pull/2272

✨(backend) allow to filter course product relation by product type

---

CHANGELOG.md
src/backend/joanie/core/api/admin.py
src/backend/joanie/core/filters/admin.py
src/backend/joanie/tests/core/test_api_admin_certificate_definitions.py
src/backend/joanie/tests/core/test_api_admin_contract_definitions.py
src/backend/joanie/tests/core/test_api_admin_course_runs.py
src/backend/joanie/tests/core/test_api_admin_courses.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/core/test_api_admin_products.py
src/backend/joanie/tests/swagger/admin-swagger.json

We need several admin api filters.
`Product.state` and `Course.state` filters are not included in this PR. Indeed, we cannot filter those fields through a simple queryset.filter and without heavy db accesses.

✨(backend) add admin api filters

---

CHANGELOG.md
src/backend/joanie/admin_urls.py
src/backend/joanie/core/admin.py
src/backend/joanie/core/api/admin.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_organization_addresses.py
src/backend/joanie/tests/core/test_api_admin_organizations.py
src/backend/joanie/tests/swagger/admin-swagger.json

We've linked `Organization` to `Address` Model with a foreign key, and we've added  the following properties on `Organization` model :
- `siret`
- `activity_number`
- `representative_profession`
- `signatory_representative` (optional)
- `signatory_representative_profession` (required when signatory_representative filled)
- `contact_phone`
- `contact_mail`
- `dpo_mail`
**All these new properties must be managed in the admin application.**

:sparkles: (backend) CRUD addresses for Organization for backoffice and admin

---

src/backend/joanie/core/api/client.py

Currently the get_zip_archive returns 500 error as the path to open the contract is wrong. Indeed the storage location should not be used to build the archive path to open.
https://gip-fun-mooc.sentry.io/issues/4947129619/?environment=preproduction&project=6599941&query=is:unresolved&statsPeriod=30d&stream_index=3

🚑(backend) fix get_zip_archive api endpoint

---

CHANGELOG.md
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/api/organizations/test_api_organizations_contract.py
src/backend/joanie/tests/core/api/organizations/test_api_organizations_course_product_relations.py
src/backend/joanie/tests/core/api/organizations/test_api_organizations_courses.py
src/backend/joanie/tests/core/api/organizations/test_list.py
src/backend/joanie/tests/core/api/organizations/test_retrieve.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/core/test_api_courses_contract.py
src/backend/joanie/tests/core/test_api_courses_order.py
src/backend/joanie/tests/swagger/swagger.json

Since we've added more properties on the Organization Model, we need to add them for the client API as well.
So far, we have added for the admin and the backoffice the management of these new properties.
Add the address field into the serializer of the OrganizationSerializer (client).
Add the other properties that are the direct attributes of the Organization model into the serializer's fields.

:sparkles: (backend) Add new properties of Organization for serializer client API

---

CHANGELOG.md
src/backend/joanie/core/models/certifications.py
src/backend/joanie/core/templates/issuers/certificate.css
src/backend/joanie/core/templates/issuers/certificate.html
src/backend/joanie/core/templates/issuers/degree.html
src/backend/joanie/core/templatetags/extra_tags.py
src/backend/joanie/core/views.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_commands_generate_certificates.py
src/backend/joanie/tests/core/test_helpers.py
src/backend/joanie/tests/core/test_models_certificate.py
src/backend/joanie/tests/core/test_models_order_get_or_generate_certificate_for_certificate_product.py
src/backend/joanie/tests/core/test_models_order_get_or_generate_certificate_for_credential_product.py
src/backend/joanie/tests/core/test_templatetags_extra_tags.py
src/backend/joanie/tests/core/test_utils_issuers_certificate_and_degree_generate_document.py

Description...
Currently, the organization bound into certificate context was the order one (picked from course organization seller).
After some review, it appears that the organization which that should be bound into context is the course author not the course selling.
As our business logic allows to define several organization as course author, we have to update our template to now support a list of organization. About the degree template, we can assume that there is always only one organization author for now.

👔(backend) bind course organizations to certificate context

---

docker-compose.yml
src/backend/joanie/settings.py
src/tray/templates/services/app/_deploy_base.yml.j2
src/tray/vars/all/main.yml

The inspect ping command is a better solution for the liveness and
readyness than using the django check command. But to do that we have to
name every worker. To this, we weill use the hostname as uniqueness as
no other worker can run on the same host in our infrastructure.
We are using a blue green infrastructure. And we have an issue with
celery in this blue green strategy. When a new stack is deploy, celery
will discover thew newly created worker and if a message is posted we
will share the same default queue name so the task can be execute
randomly on the current or next stack. By defining the default queue
name with the deployment stamp no queue can be shared anymore.

Configure celery default queue and use ping command

---

src/backend/joanie/core/api/client.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_courses_order.py
src/backend/joanie/tests/swagger/swagger.json

From the `NestedOrderCourseSerializer` endpoint, consumer api would like to get data to guess the contract signature state and the certificate state. We bind all information required to process those information.
Resolve #613

✨(backend) improve NestedOrderCourseSerializer

---

src/tray/vars/all/main.yml

for the liveness and readyness probes we were directly using the celery command but without running it in a bash command we never have the return code and we always have a timeout.

♻️(tray) run probes in a bash process

---

src/backend/joanie/core/models/contracts.py
src/backend/joanie/core/models/products.py
src/backend/joanie/signature/backends/base.py
src/backend/joanie/signature/backends/dummy.py
src/backend/joanie/signature/backends/lex_persona.py
src/backend/joanie/tests/base.py
src/backend/joanie/tests/core/api/order/test_submit_for_signature.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/signature/backends/lex_persona/test_handle_notification.py

As we have errors during signature process, our sentry issues may lack context to understand the problem.
By adding context with related contract state, we may have better debugging chances.
Could help with #595
Add extra data to logger.error, and more logger.info which will be displayed in the same sentry issue.
Sentry issue will look like this https://gip-fun-mooc.sentry.io/issues/4894381323/?environment=test&project=6599941&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=0

🔊(backend) improve logs context for signature validity

---

src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/swagger/admin-swagger.json

We recently add a field `has_consent_to_terms` to Order model and we want to display it within backoffice order detail view.

✨(backend) add has_consent_to_terms into AdminOrderSerializer

---

CHANGELOG.md
src/backend/joanie/core/views/__init__.py
src/backend/joanie/debug/urls.py
src/backend/joanie/debug/views.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/debug/test_debug_urls_template_preview.py
src/backend/joanie/tests/testing_utils.py
src/backend/joanie/urls.py

This PR will solve this [issue](https://github.com/openfun/joanie/issues/560)
Create a separte app to regroup all the preview template view in one single app. 
This app will allow the urls exclusively when the settings.DEBUG is True.

🧑‍💻 Create a Debug App to preview templates (certificate, degree, contract definition, invoice)

---

src/frontend/admin/src/components/presentational/hook-form/RHFUploadImage.tsx
src/frontend/admin/src/components/templates/organizations/form/OrganizationForm.tsx
src/frontend/admin/src/components/templates/organizations/form/translations.ts
src/frontend/admin/src/services/api/models/Organization.ts
src/frontend/admin/src/tests/course/course.test.e2e.ts
src/frontend/admin/src/tests/organization/organization.test.e2e.ts

We recently added new fields into the Organization model. The back office should display those fields and allow administrator to edit them.
Before : 
After :

✨(frontend) add organization fields

---

src/backend/joanie/edx_imports/edx_mongodb.py
src/backend/joanie/settings.py

We want to configure how the mongo read preferences to use first secondaries servers and also specify the replicaset to use.

✨(back) allow to configure mongo read preferences and replicaset

---

CHANGELOG.md
src/backend/joanie/core/filters/client.py
src/backend/joanie/tests/core/api/order/test_read_list.py
src/backend/joanie/tests/core/api/organizations/test_api_organizations_course_product_relations.py
src/backend/joanie/tests/core/api/organizations/test_api_organizations_courses.py
src/backend/joanie/tests/core/test_api_course.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/swagger/swagger.json

This PR will solve this [issue](https://github.com/openfun/joanie/issues/643).
Here are the list of expected filters by resource:
- Enrollment
- Order
- Course
- CourseProductRelation

:sparkles: (backend) API - Client - Filter enrollment, order, course and course product relations

---

src/tray/templates/services/app/_deploy_base.yml.j2

In the deployment, celery and app have the same container name. If we want to create a filter on the pod name we can't distinguish both. We add the service variant anem to the container name to allow this.

♻️(tray) rename pod name to distinguish wsgi and celery

---

src/backend/joanie/edx_imports/tasks/certificates.py
src/backend/joanie/edx_imports/tasks/universities.py
src/backend/joanie/tests/edx_imports/test_commands_migrate_universities.py
src/backend/joanie/tests/edx_imports/test_import_certificates.py
src/backend/joanie/tests/edx_imports/test_import_universities.py

When an universiy logo is not downloaded, we don't want to store the file path.

🐛(backend) do not store missing university logo

---

src/backend/joanie/edx_imports/tasks/certificates.py
src/backend/joanie/edx_imports/tasks/universities.py
src/backend/joanie/edx_imports/utils.py

With s3 storae backend, some previously used methods are not implemented. They have been replaced.

🐛(backend) fix import s3 files download

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/core/models/contracts.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_models_contract.py
src/backend/joanie/tests/swagger/swagger.json

This PR solves this [issue](https://github.com/openfun/joanie/issues/642).
Currently, a learner is not able to download a fully signed contract document. Instead, it gets a PDF generated by Joanie so without signatures.
A learner should be able to download its original contract when this one has been fully signed.
So the endpoint to download a contract should check if the related contract has been fully signed. 
Otherwise, an error response should be returned, we should retrieve the document on our signature provider and return the file in the response.

✨(backend) API - Contract Download - Learner should download

---

src/backend/joanie/edx_imports/edx_database.py
src/backend/joanie/edx_imports/tasks/users.py
src/backend/joanie/edx_imports/utils.py
src/backend/joanie/tests/edx_imports/test_commands_migrate_users.py
src/backend/joanie/tests/edx_imports/test_edx_database.py
src/backend/joanie/tests/edx_imports/test_import_users.py

Several users were not imported.
This is due to missing user preference in Open edX.
Also, celery logs were not really optimized.
When an Open edX user has no preference set,  create it, and use default language as his preferred one.
Cleanup and improve logs.

Fix migrate users

---

CHANGELOG.md
src/backend/joanie/core/api/client.py
src/backend/joanie/tests/core/test_api_certificate.py

The `CertificateViewSet` was missing a condition in its 'read_list' method (`get_queryset`) to return the certificates that are owned by a user which are linked to enrollments. Before starting the development, the 'read_list' would only return certificates that are linked to orders that are owned by a user.
To complete this, we have enhanced the queryset that is triggered in the `get_queryset` method of this viewset `CertificateViewSet`.
This feature enhances the `CertificateViewSet` to return certificates that are linked to enrollments owned by the user.
In conclusion, the `CertificateViewSet` **now returns certificates that are linked to orders and enrollments that are owned by a user.**

:sparkles: (backend) API Client -  read list - Certificate enrollments owned by user 

---

.circleci/config.yml

Ubuntu images and docker versions have been removed from circle-ci. For
both case we can use the default tags to replace them.
Also the cimg/base image has a current tag we can use to avoid to have to
update themwhen circle will decide to remove old tags.

update circle-ci removed images and docker version

---

src/backend/joanie/core/api/client.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/swagger/swagger.json

Some certificate can be link directly to an enrollment, not an order. Currently,
we do not bind enrollment information the certificate that is weird as the
frontend needs to get enrollment information to display this certificate.

✨(backend) bind enrollment into certificate serializer

---

src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/test_models_order.py

`target_course_runs` property of Order model may could return duplicated CourseRun resource. So we had a distinct method to prevent that.

🐛(backend) fix target_course_runs distinct issue

---

CHANGELOG.md
src/backend/joanie/core/api/admin.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/swagger/admin-swagger.json

This PR solves this [issue](https://github.com/openfun/joanie/issues/672).
In the Django admin, we have a custom action to cancel an order. We should port this action into our Back Office. In order to do that, an admin endpoint cancel should be created to allow to cancel an order.
With this new feature, the backoffice now has the action to cancel an order (whatever "state" the order is in at that specific time).
The method 'DELETE'' allowed for the endpoint : `/api/v1.0/admin/orders/<order_id>/`

:sparkles: (backend) Backoffice - Cancel order

---

src/backend/joanie/edx_imports/checks.py
src/backend/joanie/edx_imports/edx_database.py
src/backend/joanie/edx_imports/edx_factories.py
src/backend/joanie/edx_imports/edx_models.py
src/backend/joanie/edx_imports/edx_mongodb.py
src/backend/joanie/edx_imports/management/commands/migrate_edx.py
src/backend/joanie/edx_imports/tasks/certificates.py
src/backend/joanie/edx_imports/tasks/course_runs.py
src/backend/joanie/edx_imports/tasks/enrollments.py
src/backend/joanie/edx_imports/tasks/universities.py
src/backend/joanie/edx_imports/tasks/users.py
src/backend/joanie/edx_imports/utils.py
src/backend/joanie/tests/base.py
src/backend/joanie/tests/edx_imports/test_commands_migrate_certificates.py
src/backend/joanie/tests/edx_imports/test_commands_migrate_course_runs.py
src/backend/joanie/tests/edx_imports/test_commands_migrate_enrollments.py
src/backend/joanie/tests/edx_imports/test_commands_migrate_universities.py
src/backend/joanie/tests/edx_imports/test_commands_migrate_users.py
src/backend/joanie/tests/edx_imports/test_edx_database.py
src/backend/joanie/tests/edx_imports/test_edx_models.py
src/backend/joanie/tests/edx_imports/test_edx_mongodb.py
src/backend/joanie/tests/edx_imports/test_import_certificates.py
src/backend/joanie/tests/edx_imports/test_import_course_runs.py
src/backend/joanie/tests/edx_imports/test_import_enrollments.py

When importing Open edX data, logs were polluted with non relevant
messages. They have been improved.
When importing Open edX certificates, some useless process is done when
import should be skipped. We now skip earlier.
Adds a check to alert for course sync during import.
Adds import progression in logs.
Fix imports limits.
Fix similar resource link issue during enrollments import.
Select with order_by to allow matching limits across imports.
Find right certificate definition during certificates import.

Many migration fixes

---

src/backend/joanie/core/api/admin.py
src/backend/joanie/core/exceptions.py
src/backend/joanie/core/helpers.py
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/core/test_helpers.py
src/backend/joanie/tests/core/test_models_order_get_or_generate_certificate_for_certificate_product.py
src/backend/joanie/tests/core/test_models_order_get_or_generate_certificate_for_credential_product.py
src/backend/joanie/tests/core/test_models_order_get_or_generate_certificate_for_enrollment_product.py

On the `Order` endpoint to `generate_certificate,` we have decided to return the reason why the certificate is not allowed to be generated. This allows the frontend consumers to understand the reason why the order is not eligible at this specific time when requesting the generation of the certificate.

✨ (Backend) Backoffice - enhance exception handling to generate certificate for an order

---

src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/enums.py
src/backend/joanie/core/filters/client/__init__.py
src/backend/joanie/core/filters/client/certificate.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/swagger/swagger.json

The client certificate endpoint has a performace issue. The sql query executed is not perofrmant at all. There are a lot of join made and the where clause is filtering on two of the join made (between enrollment and user + order and user).
On the retrieve action, the username check is made once the certificate retrieve in database.
On the list action, we filter certificated linked only on order or enrollment but never both at the same time. For this, a filterset is created and customize to have the type filter with a default value on order.

⚡️(back) improve client certificate endpoint performance

---

CHANGELOG.md
src/backend/joanie/settings.py
src/backend/pyproject.toml

We want to use a redis backend for our cache in production. For this we are using django-redi library, this library is configurable with many different redis configuration. Every settings for the default cache can be configured.
https://github.com/jazzband/django-redis
Resolve #722

✨(back) add redis backend to cache configuration

---

CHANGELOG.md
env.d/development/common.dist
src/backend/joanie/core/context_processors/contract_definition.py
src/backend/joanie/core/templates/contract_definition/fragment_appendice_syllabus.html
src/backend/joanie/core/templates/contract_definition/fragment_course_plan.html
src/backend/joanie/core/templates/issuers/contract_definition.css
src/backend/joanie/core/templates/issuers/contract_definition.html
src/backend/joanie/core/utils/contract_context_processors.py
src/backend/joanie/core/utils/contract_definition.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_utils_contract_context_processors.py
src/backend/joanie/tests/core/test_utils_contract_definition_generate_document_context.py
src/backend/pyproject.toml

We would like to retrieve syllabus information from a remote Richie instance then bind those information contracts. In order to do that, from Richie, we complete the RDFa tagging on the syllabus page (https://github.com/openfun/richie/pull/2333).
Now, we implement the logic to retrieve a syllabus page from Richie then parse this document to bind syllabus into contract definition context then display it into contract template appendices.

✨(backend) bind related course syllabus into contract template

---

src/backend/joanie/core/api/admin/__init__.py

We have a flaky test related to list ordering.
It appears that the viewset ordering is missing.

🐛(backend) fix user list ordering

---

CHANGELOG.md
src/backend/joanie/core/api/admin/__init__.py
src/backend/joanie/core/helpers.py
src/backend/joanie/core/tasks.py
src/backend/joanie/core/utils/course_product_relation.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_generate_certificates.py
src/backend/joanie/tests/core/test_utils_course_product_relation.py
src/backend/joanie/tests/swagger/admin-swagger.json

New endpoint to allow the backoffice staff user to generate certificate from a course view, and launch the generation of certificates for its products relations.
To avoid having a heavy request, we decided to use celery to execute the task in background with celery.
We will create two new endpoints : 
1. To trigger the generation of certificates
2. To check the status of the ongoing generation of certificates

✨(Backend) Generate certificates from the backoffice for a course and its products relations

---

src/backend/joanie/core/templates/certificate/verify.html
src/backend/joanie/core/templates/contract_definition/fragment_appendice_syllabus.html
src/backend/joanie/core/templates/issuers/contract_definition.html
src/backend/joanie/core/templates/issuers/invoice.html

We forgot to wrap some strings into a `trans` tag

🌐(backend) add missing translation in contract template

---

src/tray/templates/services/admin/configs/admin.conf.j2

**We did this modification for local environment but not for deployment purpose.**
Currently, on the back office, if a user tries to go directly on a resource page, it gets a 404 error. As we made a static export of our next application, we can't take apart of the fallback option from the getStaticPaths method. In order to prevent to have to build our next application to run through a node server, we decide to simply add a nginx location rule to try to find the right html file for dynamic routes containing an id parameter.

🔧(tray) complete admin nginx conf

---

src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/core/utils/contract.py
src/backend/joanie/signature/management/commands/generate_zip_archive_of_contracts.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/utils/test_contract.py
src/backend/joanie/tests/swagger/swagger.json

This PR will solve this [issue](https://github.com/openfun/joanie/issues/714) 
When a user has access to several organizations and those ones are implied in the same `CourseProductRelation`, when the user asks to download an archive of all contracts, he gets all contracts from all the organizations he has access to. Before the fix, only one parameter (CPR or Org) could be used for this endpoint. Now, the endpoint accepts both parameters  `CourseProductRelation` UUID and  `Organization` UUID. Finally, only the contracts that are attached to a specific organization are now archived.
Allow the user (who has organization access) to get all archived contracts from a specific organization.
- Allow to parse 2 parameters with the endpoint to generate the archive of contracts. In the past, we only …

🐛(backend) zip archive of contract by organization

---

src/backend/joanie/core/utils/contract.py
src/backend/joanie/signature/backends/lex_persona.py
src/backend/joanie/tests/core/utils/test_contract.py
src/backend/joanie/tests/signature/backends/lex_persona/test_submit_for_signature.py

This PR solves this [issue](https://github.com/openfun/joanie/issues/713) 
To avoid the situation where the organization has not set any owner members, it causes the contract to have only the student to sign the document where we actually need the signature of both parties. The problem is that if the organization does not have at least one owner, the signature procedure will be created with only 1 signature required. We need two signatures, one from the student and one from the organization to make the contract valid.
To avoid this issue in the future, we've added a new method that will verify if there is one user with the role 'owner' for the organization that is attached to the order.
Prevent having a contract that is set as **fully signed**, but it has only been signed by the student. …

🐛(backend) prevent to sign a document when signatories are missing

---

CHANGELOG.md
src/backend/joanie/edx_imports/api/__init__.py
src/backend/joanie/edx_imports/urls.py
src/backend/joanie/tests/edx_imports/api/test_course_run.py
src/backend/joanie/urls.py

To complete the import process from edx, we need to create a new endpoint able to return a course run filter on its course_link. The course_link parameter is mandatory and the AdminCourseRunSerializer is used, it contains all the information we need in the import process. This endpoint is a server to server endpoint, the HasApiKey permission is used here.

✨(back) endpoint to retrieve a course_run filter on its course_link

---

src/backend/joanie/edx_imports/api/__init__.py
src/backend/joanie/tests/edx_imports/api/test_course_run.py

When retrieving a course_run from the endpoint made for the import, we have to exactly match the given resource_link because moodle has an incremental id, so the resource link for the id 5 can also match the one for the id 58.

🐛(back) exactly match resource_link when retrieving a course run

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/api/order/test_withdraw.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/swagger/swagger.json

Before the withdrawal date, users can withdraw their order.
Add an API endpoint to withdraw an order.

✨(backend) add order withdraw api endpoint

---

docs/explanation/signature_backend.md
src/backend/joanie/core/models/contracts.py
src/backend/joanie/core/models/products.py
src/backend/joanie/settings.py
src/backend/joanie/signature/backends/lex_persona.py
src/backend/joanie/tests/core/api/order/test_submit_for_signature.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_models_contract.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/signature/backends/lex_persona/test_delete_signing_procedure.py
src/backend/joanie/tests/signature/backends/lex_persona/test_get_signature_invitation_link.py
src/backend/joanie/tests/signature/backends/lex_persona/test_get_signed_file.py
src/backend/joanie/tests/signature/backends/lex_persona/test_handle_notification.py
src/backend/joanie/tests/signature/backends/lex_persona/test_submit_for_signature.py
src/backend/joanie/tests/signature/test_backend_signature_base.py

Currently the document uploaded on the signature provider has the contract definition title as title. This is weird as for a course, all contracts will have the same name. In order to improve that we decide to built a specific title according to the current date, the related course and the order primary key.
`YYYY-MM-DD_COURSE_CODE_ORDER_PK`
On Lex Persona, each workflow steps have a validity period. We sets this one according to the settings `JOANIE_SIGNATURE_VALIDITY_PERIOD` but this setting is expressed in seconds and it appears Lex Persona expects a duration in ms. So as effect, the minimum validity period of Lex persona is used (which is 24h). Once this delay is reached, Lex Persona stops the related workflow and recipients are not able to sign until we restart the worfklow. …

🐛(backend) convert validity period in ms for Lex Persona backend

---

CHANGELOG.md
src/backend/joanie/edx_imports/tasks/enrollments.py
src/backend/joanie/tests/edx_imports/test_import_enrollments.py

When importing enrollments, a same insert in the database in a race condition leading to an integrity error. Unfortunately, the whole batch of 1000 enrollments is not inserted at allt. Using the parameter ignore_conflicts fix this issue by ignoring already inserted record but still inserting not existing enrollments.

🐛(edx_import) ignore conflicts when creating batch of enrollments

---

CHANGELOG.md
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_create.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_list.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_retrieve.py
src/backend/joanie/tests/core/api/admin/course_product_relations/test_update.py
src/backend/joanie/tests/core/test_api_admin_products.py
src/backend/joanie/tests/swagger/admin-swagger.json

Previously, we were using specific serializers to bind course relations and product relations in respective serializers. Now, we would like to be able to create/update product's course relations but the route in charge to create those relations is a nested one under course resource so currently course information are not returned in the response but we need those information from product detail view. That's why we decided to share the same serializer to return relation of Course or Product.

♻️(backend) use same serializer for product and course relations

---

src/backend/joanie/lms_handler/backends/moodle.py
src/backend/joanie/tests/lms_handler/test_backend_moodle.py

Each time a user is not found on Moodle, a logger.error message is sent. That means that for all new users, an event will be sent that is weird. In order to fix that, we decrease the log level to info. In this way, this log will be bound
to an error event if needed.

🔇(moodle) remove error logs when user is not found

---

CHANGELOG.md
src/backend/joanie/core/admin.py
src/backend/joanie/tests/core/admin/test_enrollment.py

For the django backoffice, when we use the search bar, there was an error thrown where it cannot resolve the keyword 'organization' into the fields. The path to obtains the organization field was not set up properly in the search fields of the admin class. 
To use the search bar on the enrollment view of the django backoffice, we have to set a User first (`RequiredUserFilter`) and then add the string in the search bar that we want. The options available are : by username, by email, by course title and finally by organization.

🐛(backend) enrollment search by query string for backoffice django

---

CHANGELOG.md
src/backend/joanie/core/templates/admin/base.html
src/backend/joanie/core/templates/debug/sentry_decrypt.html
src/backend/joanie/core/utils/newsletter/brevo.py
src/backend/joanie/core/utils/sentry.py
src/backend/joanie/debug/views.py
src/backend/joanie/settings.py
src/backend/joanie/tests/base.py
src/backend/joanie/tests/core/utils/newsletter/test_brevo.py
src/backend/joanie/tests/core/utils/test_sentry.py
src/backend/joanie/urls.py
src/backend/pyproject.toml

When analyzing sentry logs, we captured some issues:
- non relevant errors sent during newsletter subscription
- sensitive data sent (celery task arguments)
As those sensitive data were crucial for debugging a real problem, all contexts are encrypted.
An admin page is added to decrypt them

Encrypt celery additional data

---

CHANGELOG.md
src/backend/joanie/core/models/accounts.py
src/backend/joanie/tests/core/test_models_user.py

As we are creating user on the fly during api requests, sometimes we can try to create a user twice. In this case `save` method raise an IntegrityError but as the subscription logic is put before the model save, this one is executed even if the save fails that is weird.

🐛(user) prevent newsletter subscription created twice on user creation

---

CHANGELOG.md
docs/explanation/lex-persona.md
docs/explanation/signature_backend.md
src/backend/joanie/core/api/admin/__init__.py
src/backend/joanie/core/tasks.py
src/backend/joanie/core/utils/contract.py
src/backend/joanie/signature/backends/base.py
src/backend/joanie/signature/backends/dummy.py
src/backend/joanie/signature/backends/lex_persona.py
src/backend/joanie/tests/core/test_api_admin_organization_access.py
src/backend/joanie/tests/core/utils/test_contract.py
src/backend/joanie/tests/signature/backends/lex_persona/test_update_organization_signatories.py
src/backend/joanie/tests/signature/test_backend_signature_dummy.py

New organization owners should be able to sign the contract. Actually, the invitation link received by the signature backend will only return the link if the user has been registered into the signature procedure. Actually, a new organization owner will never be able to sign existing contracts that were initiated before his arrival. 
We need to be able to catch every update, deletion or creation of **organization access** with the role 'owner' to update the list of signatories for an organization for ongoing signature procedures.
Allow new organization owners to be able to sign existing contract that were initiated before their arrival.
Owners who are deleted should be taken of the signature procedures as well.
The goal is to have only users who are eligible to date to sign contracts in …

✨(backend) new organization owner can sign contract

---

CHANGELOG.md
src/backend/joanie/core/templates/contract_definition/fragment_appendice_syllabus.html
src/backend/joanie/core/utils/contract_context_processors.py
src/backend/joanie/tests/core/test_utils_contract_context_processors.py

There are two new sections in the course syllabus of Richie that we need to extract the information through RDF attributes for our contract_definition context. We've updated the processor context for the accessibility section, and for the required equiment it was already in gathered through the 'about' section.
Fix #764
Add the new section that were added into Richie's course syllabus (Accessibility and Required Equipment).

✨(backend) Template - Update Contract Definition template with new sections (Accessibility and Required Equipment)

---

CHANGELOG.md
src/backend/joanie/core/templatetags/extra_tags.py
src/backend/joanie/core/utils/contract_definition.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/core/utils/test_contract_definition_generate_document_context.py
src/backend/joanie/tests/core/utils/test_issuers_contract_definition_generate_document.py

On the contract template, the **hours** and the **dates** were not rendered as expected once it was generated. 
To avoid facing this situation, we now transform those values of **dates** and **duration** into iso 8601 string format before returning the context. We want the value to be prepared at their creation before adding it to the contract.
Overall, we had to update the : `course_start`, `course_end`, `course_effort` and `course_price`.
Make sure that our **template tags** for **date** and **duration** iso 8601 will work as expected into the template rendering. They are both waiting for the incoming input value to be **strings** and not **datetime.datetime**, or **datetime.date**, and not **datetime.timedelta**.
Since we prepare the context that way it should be saved into the …

🐛(backend) contract context for the course section data as strings (price, effort, course start, course end)

---

CHANGELOG.md
src/backend/joanie/core/utils/sentry.py
src/backend/joanie/tests/core/utils/test_sentry.py

If the logging secret key is misconfigured, currently log events are not sent to
our error tracking platform that is weird. So this setting is misconfigured we
manage the error and instead of binding encrypted data we bind an error
dictionary to mention that encryption failed.

🐛(backend) manage invalid logging secret key

---

CHANGELOG.md
src/frontend/admin/src/components/presentational/hook-form/RHFDateTimePicker.tsx
src/frontend/admin/src/components/testing/presentational/hook-form/RHFDateTimePicker/RHFDateTimePicker.spec.e2e.tsx
src/frontend/admin/src/components/testing/presentational/hook-form/RHFDateTimePicker/RHFDateTimePickerTestWrapper.tsx

Currently, when you click on a datepicker input and modify the date with the keyboard by deleting the month for example, a fatal error occurs.

🐛(frontend) fix bug update DatePicker with keyboard

---

CHANGELOG.md
src/frontend/admin/src/components/templates/orders/view/OrderView.tsx
src/frontend/admin/src/services/api/models/Order.ts
src/frontend/admin/src/tests/orders/OrderTestScenario.ts
src/frontend/admin/src/tests/orders/orders.test.e2e.ts

When an order is in draft without organization for example, a fatal error occurs
Close #784

🐛(frontend) fix order view when organization is undefined

---

CHANGELOG.md
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/api/order/test_abort.py
src/backend/joanie/tests/core/api/order/test_create.py
src/backend/joanie/tests/core/api/order/test_read_detail.py
src/backend/joanie/tests/core/api/order/test_read_list.py
src/backend/joanie/tests/core/api/order/test_update.py
src/backend/joanie/tests/swagger/swagger.json

We want to be able to retrieve order payment schedule if there is one through the order api client.

✨(backend) add payment_schedule field to OrderSerializer

---

CHANGELOG.md
src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductFormTargetCourseRow.tsx
src/frontend/admin/src/tests/product/product.test.e2e.ts

On product detail target course tab, we should display a visual indicator to distinguish graded target courses from others.

✨(frontend) add is graded indicator inside product detail view

---

src/backend/joanie/core/models/products.py
src/backend/joanie/core/tasks/payment_schedule.py
src/backend/joanie/core/utils/payment_schedule.py
src/backend/joanie/payment/backends/base.py
src/backend/joanie/payment/backends/dummy.py
src/backend/joanie/payment/backends/lyra/__init__.py
src/backend/joanie/payment/backends/payplug/__init__.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/tasks/test_payment_schedule.py
src/backend/joanie/tests/core/test_utils_payment_schedule.py
src/backend/joanie/tests/payment/test_backend_base.py
src/backend/joanie/tests/payment/test_backend_dummy_payment.py
src/backend/joanie/tests/payment/test_backend_lyra.py
src/backend/joanie/tests/payment/test_backend_payplug.py

In order to identify every installments in an order schedule, we add a
unique id that can be use to find it later.
When an installment is paid, we can now use it in the
payment backend for all existing payment method (create_payment,
create_one_click_payment and create_zero_click_payment). Doing this, the
`_do_on_payment_success` and `_do_on_payment_failure` methods are able
to manage an installment lifecycle. There is no more need to manage it
in the payment schedule task.

Ease installment identification and propage installment in payment backend

---

CHANGELOG.md
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/api/order/test_read_detail.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/swagger/swagger.json

When retrieving payment schedule, our API consumer needs to know what is the currency used. So we add a field `amount_currency` to pass this information.

✨(api) add `amount_currency` field to `OrderPaymentSerializer`

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/models/products.py
src/backend/joanie/payment/models.py
src/backend/joanie/tests/core/api/order/test_submit_installment_payment.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/payment/test_models_credit_card.py
src/backend/joanie/tests/swagger/swagger.json

New endpoint to pay a failed installment payment that was scheduled on an order. If the `card_id` is given, then the payment will go through the `create_one_click_payment`. Else, if no `card_id` is passed in the payload, the endpoint will use `create_payment` method. In order to simplify our code on the ownership of a credit card, we have decided to add a new Manager class for the `CreditCard` model. The manager class has one method that retrieves the credit card object if the queryset matches the input `card_id` and the `owner_id`.

✨(backend) pay failed installment in payment schedule of an order

---

src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/api/order/test_read_detail.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/swagger/swagger.json

We recently refactor installment to add an id. We want to add this field into the related serializer.

✨(backend) add id field to OrderPaymentSerializer

---

src/backend/joanie/core/flows/order.py
src/backend/joanie/demo/management/commands/create_dev_demo.py
src/backend/joanie/tests/core/test_flows_order.py

Some state source were missing for `complete` and `pending_payment` transition. We fix that.
Furthermore, we recently create a failed installment payment order but we forgot to link an invoice to this order, so it leads to issues when trying to use this order for development.
Description...

🧑‍💻(backend) complete no payment order

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/payment/backends/lyra/__init__.py
src/backend/joanie/tests/core/api/order/test_submit_installment_payment.py
src/backend/joanie/tests/payment/test_backend_lyra.py

Allow user to submit installment payment when the order's first installment has not been paid yet. Before the update, only orders with the state `failed_payment` were expected for the endpoint `submit_installment_payment` in the OrderViewSet, now we also allow the state `no_payment` of an order (where the first installment has failed to be paid in the payment schedule).

✨(backend) submit installment payment when order is `no_payment` state

---

CHANGELOG.md
src/backend/joanie/payment/api.py
src/backend/joanie/payment/backends/base.py
src/backend/joanie/payment/backends/dummy.py
src/backend/joanie/payment/backends/lyra/__init__.py
src/backend/joanie/tests/payment/test_api_credit_card.py
src/backend/joanie/tests/payment/test_backend_base.py
src/backend/joanie/tests/payment/test_backend_dummy_payment.py
src/backend/joanie/tests/payment/test_backend_lyra.py
src/backend/joanie/tests/swagger/swagger.json

A user should be allowed to add new credit card by tokenizing his credit card through the payment backend. It allows the user to have multiple credit cards to manage his purchases.

✨(backend) endpoint to tokenize a credit card with payment backend

---

CHANGELOG.md
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/api/organizations/test_api_organizations_contract.py
src/backend/joanie/tests/core/test_api_certificate.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_courses_contract.py
src/backend/joanie/tests/swagger/swagger.json

Frontend consumer needs to use state order field no matter the order is nested within another resource or not.

✨(backend) add state field to NestedOrderSerializer

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/payment/backends/lyra/__init__.py
src/backend/joanie/payment/exceptions.py
src/backend/joanie/tests/core/api/order/test_submit_installment_payment.py
src/backend/joanie/tests/payment/test_backend_lyra.py
src/backend/joanie/tests/swagger/swagger.json

This PR will solve the following issues : #811 , #813 
If there is an error, the payment provider should raise an exception. 
With an exception, the error never silently fails, it can prevent or at least show a bug.
We have implemented a custom exception that will raise when an request fails on the payment provider API side.
The exception is captured when a request failed on the following payment backend methods : `create_payment`, `create_one_click_payment` and `create_zero_click_payment`.
When calling the endpoint `submit_installment_payment` and an error occurs on the API of the payment provider, a `400 BAD_REQUEST` is raised.
I've checked for payplug payment provider, there is already a BadRequest exception raised when failling with a request with the API of **Payplug**. Only **Lyra** …

🐛 (backend) Error with payment provider are raised and not fail silently

---

CHANGELOG.md
src/backend/joanie/lms_handler/backends/moodle.py
src/backend/joanie/tests/core/test_flows_order.py

Currently, in MoodleBackend,  if during a `set_enrollment`, a user must be created and this task failed, a MoodleUserCreateException is raised. This exception is not caught by the method `set` of the Enrollment model and it should not be manage as this is too specific exception. But currently, if this error is raised when we try to auto enroll a user during an order validation, the order validation can be rollback. That's why we have to
improve this error management and raise an EnrollmentError instead.
https://gip-fun-mooc.sentry.io/issues/5141416829/?environment=preproduction&project=6599941&query=is:unresolved+issue.priority:%5Bhigh,+medium%5D&statsPeriod=90d&stream_index=7&utc=true

🐛(backend) moodle user creation must raise EnrollmentError exception

---

.circleci/config.yml

The pylint CI job dedicated for the development branch is not running.
Update the branch pattern to allow todos in pylint.

Dev /fix lint todo

---

CHANGELOG.md
src/backend/joanie/core/templates/issuers/certificate.html
src/backend/joanie/tests/core/utils/test_issuers_certificate_and_degree_generate_document.py

In a sentence, organization was not bound properly.

🐛(backend) fix certificate template

---

CHANGELOG.md
src/backend/joanie/core/models/certifications.py
src/backend/joanie/core/templates/issuers/certificate.html
src/backend/joanie/core/templates/issuers/degree.html
src/backend/joanie/tests/core/test_models_certificate.py

When the `organization.logo` is `None`, a `<img>` tag is rendered  `None` actually. We do not want this anymore. We should trigger a message when generating the certificate's context if an organization does not have a logo for itself.

🐛(backend) certificate template do not render <img> tag if organization has no logo

---

CHANGELOG.md
src/backend/joanie/core/filters/client/certificate.py
src/backend/joanie/tests/core/test_api_certificate.py

With the data migration, we imported degrees and attestation of achievement. To prevent to have to create all the data structure (product, product course relation, orders), for degrees, we simply linked them to their enrollment and we used a "degree" certificate template. But there is one drawback to do that, the api allows to filter certificates according to their relation to order and enrollment models. In short, imported degrees are currently returned with legacy attestation of achievement. In order to fix that, we propose to tweak the certificate filter to include those specific degrees with order certificates

👔(backend) certificate order filter return enrollment degrees

---

CHANGELOG.md
src/backend/joanie/core/utils/payment_schedule.py
src/backend/joanie/payment/__init__.py
src/backend/joanie/settings.py
src/backend/joanie/tests/payment/test_get_country_calendar.py

This PR will solve the [issue](https://github.com/openfun/joanie/issues/789) 
We have added two new settings to be able to choose the **calendar country** depending on where the application is used geographically. The setting variable is called : `JOANIE_CONTRACT_COUNTRY_CALENDAR`. To get the instance of calendar set in settings, it can be retrieved by using the method : `get_country_calendar()`
The other setting allows (`JOANIE_CONTRACT_COUNTRY_CALENDAR`) to set the period of days a consumer has the right to withdraw from a contract. 
The calendar was set to **France** and the **withdrawal period of days** (16 days for French context) was **hard coded** into the method : 
```python
def _withdrawal_limit_date(signed_contract_date, course_start_date):
...
```
Give more flexibility to set …

✨(backend) allow to configure how the withdrawal data is computed

---

CHANGELOG.md
src/backend/joanie/core/flows/order.py
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/test_flows_order.py

Currently, when an order is canceled or validated, we update the enrollment mode . (e.g: For OpenEdx, from honor to verified on order validation). Currently the queryset to retrieve enrollments is wrong. Instead of retrieving user enrollment for the related order, it retrieves all active enrollments related to the course to which the order is linked...

🚑(backend) fix enrollment mode update on order validation

---

CHANGELOG.md
src/backend/joanie/core/flows/order.py
src/backend/joanie/signature/backends/base.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/signature/test_backend_signature_base.py

On order validation, the `enroll_user_to_course_run` is triggered and sometimes this one can raise exception. In atomic transition context, this is weird as it causes the rollback of database changes and from api point of view the endpoint returns an internal server error... As this method can be considered of a side effect it should impact nothing if it fails. In order to fix that, we catch all exception raised by this method and just send an error log to Sentry.

🐛(backend) prevent automatic enrollment failure to raise error

---

CHANGELOG.md
src/backend/joanie/lms_handler/backends/openedx.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/lms_handler/test_backend_openedx.py

On an OpenEdX enrollment, if we try to update an already up-to-date enrollment, OpenEdX currently return a 400 Bad request that raises an EnrollmentError on our side. To prevent that, before executing the post request, we get the enrollment to check if its mode or its active state needs to be updated

👔(backend) do not update up-to-date OpenEdX enrollment

---

CHANGELOG.md
src/frontend/admin/src/components/templates/orders/list/OrdersList.tsx
src/frontend/admin/src/tests/orders/orders.test.e2e.ts

In backoffice, adding created_on date to orders would allow us to better track payments.
Add created_on column on order list view

✨(frontend) add created_on date on orders

---

CHANGELOG.md
arnold.yml
src/backend/joanie/lms_handler/backends/openedx.py
src/backend/joanie/tests/lms_handler/test_backend_openedx.py
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

To choose the enrollment mode to use when enrolling a user on OpenEdX course run
we currently check if a validated order relying on this enrollment exist. But
to retrieve this order we don't filter order owned by the enrollment user so in
case of credential product once one validated order exists, all other user
enrolling to the related course run was enrolled with verified mode...
Then release a patch version

🚑(backend) fix openedx set enrollment mode choice logic

---

CHANGELOG.md
src/backend/joanie/core/tasks/payment_schedule.py
src/backend/joanie/payment/backends/dummy.py
src/backend/joanie/tests/core/tasks/test_payment_schedule.py
src/backend/joanie/tests/payment/test_backend_dummy_payment.py

When the due date has come, the task `process_today_installment` now verifies if there are previous installments on the order that require a payment. Now, the task will trigger a payment for the installments that are in the past that are not yet paid.

✨(backend) catch up on late payment schedule event

---

src/backend/joanie/signature/backends/dummy.py
src/backend/joanie/tests/core/api/order/test_submit_for_signature.py
src/backend/joanie/tests/core/api/organizations/test_contracts_signature_link.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/core/test_models_organization.py
src/backend/joanie/tests/signature/test_backend_signature_dummy.py
src/frontend/admin/src/components/templates/orders/view/translations.tsx
src/frontend/admin/src/services/api/models/Order.ts

1. We recently remove the automatic update of contract when an API consumer request
an invitation link with the dummy signature backend. That means now, the API
consumer has to call manually the notification endpoint to confirm the
signature but some information where missing to update properly the contract,
so we complete the invitation_link method to bind missing information.
2. Then we recently add a new order state: "signing". But we do not update the admin
application accordingly, so order views were broken when a signing order must be
displayed.

🐛(backend) fix handle_notification of dummy signature backend

---

src/backend/joanie/core/factories.py
src/backend/joanie/core/flows/order.py
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/api/order/test_submit_for_signature.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/core/test_models_order.py

Currently, an order in pending state is able to transition to pending_payment once no installment has been refused. That means we are able to transition to this state order to which we never try to pay an installment that is weird. Indeed, only orders with the first installment paid and all others installment not refused should be allowed to transition to pending_payment state

👔(backend) update condition to transition order to pending_payment

---

Dockerfile
renovate.json
src/backend/pyproject.toml

Upgrade Weasyprint to version 62.

⬆️(backend) upgrade Weasyprint to latest version

---

CHANGELOG.md
src/backend/joanie/edx_imports/edx_mongodb.py
src/backend/joanie/edx_imports/management/commands/populate_certificate_signatory.py
src/backend/joanie/edx_imports/tasks/__init__.py
src/backend/joanie/edx_imports/tasks/certificates.py
src/backend/joanie/edx_imports/utils.py
src/backend/joanie/tests/edx_imports/test_commands_migrate_certificates.py
src/backend/joanie/tests/edx_imports/test_commands_populate_signatory_certificates.py
src/backend/joanie/tests/edx_imports/test_edx_mongodb.py
src/backend/joanie/tests/edx_imports/test_import_certificates.py
src/backend/joanie/tests/edx_imports/test_populate_signatory_certificates.py

Currently, on certificate import, most of the time, we are not able to retrieve
certificate signatory. It appears that the Mongo DB request to get this data is
wrong. So we fix this method to retrieve signatory information.

🐛(edx_imports) fix signatories retrieval

---

src/tray/templates/services/app/cronjob_process_payment_schedules.ym.j2
src/tray/vars/all/main.yml

We have to add a cronjob in the tray to manage the process_payment_schedule management command.

🔧(tray) add cronjob for process_payment_schedule management command

---

src/tray/templates/services/app/job_db_migrate.yml.j2

Currently, the env configMap volume is not mounted but we need it to be able to access to S3 Storage.

🔧(tray) add configMap env into db_migrate job

---

CHANGELOG.md
src/frontend/admin/src/components/templates/orders/view/OrderView.tsx
src/frontend/admin/src/components/templates/orders/view/translations.tsx
src/frontend/admin/src/services/api/models/Order.ts
src/frontend/admin/src/services/factories/orders/index.ts

With the new workflow, the order field has_consent_to_terms has been deprecated so we can remove it from the order detail view in the BO application

🔥(admin) remove has_consent_to_terms

---

CHANGELOG.md
src/backend/joanie/core/flows/order.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/utils/payment_schedule.py
src/backend/joanie/tests/core/api/order/test_create.py
src/backend/joanie/tests/core/api/order/test_payment_method.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/core/test_models_order.py

Currently, the payment schedule was generated on the signature submit. But this was weird as some product can have no contract and in this case, no payment schedule is generated. So in order to support this kind of product, we move the payment schedule generation logic on pending transition success.

✨(backend) allow to generate payment schedule for any kind of product

---

CHANGELOG.md
src/backend/joanie/core/management/commands/process_payment_schedules.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/tasks/payment_schedule.py
src/backend/joanie/core/utils/payment_schedule.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/tasks/test_payment_schedule.py
src/backend/joanie/tests/core/test_commands_process_payment_schedules.py
src/backend/joanie/tests/core/test_utils_payment_schedule.py

`find_today_installments` currently retrieve only installments which have a due_date sets to today. Instead we would like to retrieve all installements which are due to payment today.

👔(backend) update find_today_installments to retrieve past due payment

---

src/backend/joanie/core/utils/payment_schedule.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/test_utils_payment_schedule.py

The payment schedule dates were wrong when the withdrawal date was after the session start date.

    🐛(backend) fix payment schedule date calculation

---

CHANGELOG.md
env.d/development/common.dist
src/backend/joanie/core/flows/order.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/templatetags/extra_tags.py
src/backend/joanie/debug/urls.py
src/backend/joanie/debug/views.py
src/backend/joanie/payment/backends/base.py
src/backend/joanie/payment/backends/dummy.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/core/test_templatetags_extra_tags.py
src/backend/joanie/tests/payment/base_payment.py
src/backend/joanie/tests/payment/test_backend_base.py
src/backend/joanie/tests/payment/test_backend_dummy_payment.py
src/backend/joanie/tests/payment/test_backend_lyra.py
src/backend/joanie/tests/payment/test_backend_payplug.py
src/mail/mjml/installment_paid.mjml
src/mail/mjml/installments_fully_paid.mjml
src/mail/mjml/partial/header.mjml
src/mail/mjml/partial/installment_table.mjml

This PR will solve this [issue](https://github.com/openfun/joanie/issues/862) 
Actually, we only send an email confirming that the order is validated. This behaviour is useful when a user purchases a certificate for example.
But since we have added payment schedules for all order in a near future, we should trigger an email each time the user has paid successfully an installment. We must preserve the first email that is initially sent once the order is validated. We now also send a different email when the user has paid all the installments on the payment schedule.

:sparkles: (backend) Mail when installment debit has succeed 

---

CHANGELOG.md
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_enrollment.py

On enrollment order resource, our api consumer needs to be able to retrieve payment schedule information so we update the OrderLightSerializer to add this field.

✨(backend) bind payment_schedule into OrderLightSerializer

---

CHANGELOG.md
src/backend/joanie/core/utils/emails.py
src/backend/joanie/debug/urls.py
src/backend/joanie/debug/views.py
src/backend/joanie/payment/backends/base.py
src/backend/joanie/payment/backends/dummy.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/utils/test_emails_prepare_context_data.py
src/backend/joanie/tests/payment/base_payment.py
src/backend/joanie/tests/payment/test_backend_base.py
src/backend/joanie/tests/payment/test_backend_dummy_payment.py
src/backend/joanie/tests/payment/test_backend_lyra.py
src/backend/joanie/tests/payment/test_backend_payplug.py
src/mail/mjml/installment_paid.mjml
src/mail/mjml/installment_refused.mjml
src/mail/mjml/installments_fully_paid.mjml
src/mail/mjml/partial/welcome.mjml

This PR will solve this [issue](https://github.com/openfun/joanie/issues/863)
When an installment debit has failed, we need to inform the user with an email about the failed payment.

✨ (backend) Mail when installment debit has failed

---

CHANGELOG.md
src/backend/joanie/signature/backends/lex_persona.py
src/backend/joanie/tests/signature/backends/lex_persona/test_handle_notification.py

Currently, when your signature provider sends a notification, if our internal logic raise an error, an error HTTP Response is returned. Then the signature provider will retry to send this notification and it could lead to heavy latency to receive other notification. So we improve error catching from your side to prevent to return Error HTTP response if an error is raised from an internal server error.

🥅 (backend) improve error catching of signature notification

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/tests/core/api/order/test_submit.py

~Currently, except draft orders all other must have an organization set but in
order to improve the round robin logic to set order organization we would like
to unset organization when a order transitions to pending state. So we update
logic to allow to have an empty organization if its state is
draft/pending/canceled.~ *This implementation has been postponed to prevent a migration which mess up the rebase with the development branch...*
So now when an order is submit, if it has no organization or if its state is pending, we (re)assign an organization.
Furthermore, we exclude pending order from the `order_count` annotation.
Then last fix to do, we want favor "author" organization in case of order_count equality.

👔(backend) change logic to set order organization on submitting 

---

CHANGELOG.md
src/backend/joanie/core/exceptions.py
src/backend/joanie/core/factories.py
src/backend/joanie/core/fields/schedule.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/utils/payment_schedule.py
src/backend/joanie/tests/core/api/order/test_submit_installment_payment.py
src/backend/joanie/tests/core/api/organizations/test_contracts_signature_link.py
src/backend/joanie/tests/core/models/order/test_factory.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/tasks/test_payment_schedule.py
src/backend/joanie/tests/core/test_api_contract.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/core/test_utils_payment_schedule.py
src/backend/joanie/tests/core/utils/test_emails_prepare_context_data.py
src/backend/joanie/tests/payment/test_backend_base.py

The **OrderPaymentScheduleDecoder** was returning a **string representation** of the due_date **instead** of a **datetime.date object**. This behavior complicated **comparisons** and **operations**, as handling both strings and date objects increased the complexity for nothing.
To simplify date **handling** and ensure **consistency**, a transformation was added to the decoder, converting the string from the database into a datetime.date object.

✨(backend) Ensure due_date in payment schedule decoder returns a date object

---

CHANGELOG.md
src/backend/joanie/core/management/commands/send_mail_upcoming_debit.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/tasks/payment_schedule.py
src/backend/joanie/core/utils/emails.py
src/backend/joanie/core/utils/payment_schedule.py
src/backend/joanie/debug/urls.py
src/backend/joanie/debug/views.py
src/backend/joanie/payment/backends/base.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/tasks/test_payment_schedule.py
src/backend/joanie/tests/core/test_commands_send_mail_upcoming_debit.py
src/backend/joanie/tests/core/test_utils_payment_schedule.py
src/backend/joanie/tests/core/utils/test_emails_prepare_context_data.py
src/backend/joanie/tests/payment/test_backend_base.py
src/mail/mjml/installment_reminder.mjml
src/tray/templates/services/app/cronjob_send_mail_upcoming_debit.yml.j2
src/tray/vars/all/main.yml

This PR will solve this [issue](https://github.com/openfun/joanie/issues/864)
We need to notify the order's owner that an upcoming installment payment debit will happen soon on their
credit card.
The reminder frequency that is set in days will be a configuration setting. 
By default, it will be 2 days by default in JOANIE settings.

✨ (backend) Mail reminder upcoming debit installment payment

---

CHANGELOG.md
src/backend/joanie/core/flows/order.py
src/backend/joanie/tests/core/api/order/test_payment_method.py
src/backend/joanie/tests/core/test_flows_order.py

When we generate the payment schedule and if the course has already started,
the 1st installment due date of the order's payment schedule will be set to the current
day. Since we only debit the next night through a cronjob, we need be able to make the
user pay to have access to his course, and avoid that the has to wait the next
day to start it.

:sparkles:(backend) debit installment on order pending transition if due date is current day

---

src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/tests/core/api/order/test_create.py

Due to sales tunnel version 2 changes, we had to revert commits from https://github.com/openfun/joanie/pull/926 and rewrite them to match the new order states.

Dev /restore order organization set

---

src/backend/joanie/core/factories.py
src/backend/joanie/demo/management/commands/create_dev_demo.py
src/backend/joanie/tests/core/api/order/test_payment_method.py
src/backend/joanie/tests/core/api/order/test_read_list.py
src/backend/joanie/tests/core/api/order/test_submit_installment_payment.py
src/backend/joanie/tests/core/models/order/test_factory.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/lms_handler/test_backend_openedx.py
src/backend/joanie/tests/payment/test_backend_base.py

In a past [PR](https://github.com/openfun/joanie/pull/916), we have added in the `post_transition_success` of the **order flows** to enable a payment for the user if the course has already started (and the 1st installment due date is on the current day), which allows the student to enter the course directly instead of waiting overnight.
By adding this new transition action when the state goes from `to_save_payment_method` to `pending`, it seems like somes tests failed suddenly after the branch being merged to `dev` branch. 
We've decided to fix the `OrderFactory` class by creating main invoice when the order is not in state `draft`. 
It eases the life of developers while testing that specific state for an order,  they won't have to create the main invoice by hand in a test after creating …

✅(backend) Fix failing tests due to missing updates of the `OrderFactory` and improve `OrderGeneratorFactory`

---

.circleci/config.yml

remote_docker version 20.10.23 has been deprecated. We use the `default` version to prevent future issue of this kind.

💚(circleci) upgrade remote_docker for hub

---

CHANGELOG.md
src/backend/joanie/core/factories.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/templates/issuers/contract_definition.css
src/backend/joanie/core/templates/issuers/contract_definition.html
src/backend/joanie/core/utils/contract_definition.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/utils/test_contract_definition_generate_document_context.py
src/backend/joanie/tests/core/utils/test_issuers_contract_definition_generate_document.py

For legal purpose, we must display the order payment schedule in the training
contract that's why we bind this information into the contract template.
Furthermore, we move the signature fields before appendices section.
[contract-example.pdf](https://github.com/user-attachments/files/17248254/contract-example.pdf)

✨(backend) display payment schedule in contract template 

---

src/backend/joanie/core/admin.py

As we have a very large amount of enrollments in our staging and production database, we can't display them all in a select box. Using an autocomplete field prevent this.

🐛(backend) do not list all enrollments in admin order view

---

CHANGELOG.md
docs/explanation/lex-persona.md
docs/explanation/signature_backend.md
src/backend/joanie/signature/backends/base.py
src/backend/joanie/signature/backends/dummy.py
src/backend/joanie/signature/backends/lex_persona.py
src/backend/joanie/tests/core/api/order/test_lifecycle.py
src/backend/joanie/tests/core/api/order/test_submit_for_signature.py
src/backend/joanie/tests/core/models/order/test_factory.py
src/backend/joanie/tests/core/test_models_order.py
src/backend/joanie/tests/signature/backends/lex_persona/__init__.py
src/backend/joanie/tests/signature/backends/lex_persona/test_handle_notification.py
src/backend/joanie/tests/signature/backends/lex_persona/test_submit_for_signature.py
src/backend/joanie/tests/signature/backends/lex_persona/test_update_organization_signatories.py
src/backend/joanie/tests/signature/test_backend_signature_base.py

Currently, on LexPersona backend, we validate student signature on `recipientFinished` event and organization signature on `workflowFinished` event. This is weird as when an organization signs, two events are sent by LexPersona (`recipientFinished` + `workflowFinished`). As consequence, when the organization signs, `student_signed_on` is updated on `recipientFinished` event and `organization_signed_on` is set on `workflowFinished`. So in order to fix that, we do not use anymore the `workflowFinished` event. Instead, as our workflow is static, we can assume to set `student_signed_on` on the first `recipientFinished` event then set `organization_signed_on` the second time we receive a `recipientFinished` event for the related contract.

👔(backend) update `handle_notification` signature backend logic

---

CHANGELOG.md
src/backend/joanie/payment/backends/base.py
src/backend/joanie/payment/backends/lyra/__init__.py
src/backend/joanie/settings.py
src/backend/joanie/tests/payment/test_backend_base.py

Sometime error can be raised as our payment backend reached the request timeout sets to 5s. So we make this value configurable to be able to increase it with ease.

✨(backend) make backend request timeout configurable

---

CHANGELOG.md
src/backend/joanie/payment/backends/lyra/__init__.py
src/backend/joanie/tests/payment/test_backend_lyra.py

Currently, if a zero click payment is refused, our logic can consider this one as accepted as we are checking the wrong response attribute...

🚑(backend) manage refused zero click payments

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
arnold.yml
docker/images/admin/Dockerfile
src/backend/joanie/core/flows/order.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Currently, it is not possible to transition from `no_payment` state to
`completed` state. But this should be possible to manage orders with a single
installment which was refused and has been fixed.
Then release joanie 2.9.2.

🐛(backend) fix order lifecycle issue

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/api/order/test_create.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_models_course_product_relation.py
src/backend/joanie/tests/core/test_models_product.py
src/backend/joanie/tests/swagger/swagger.json

We recently add a property `is_withdrawable` to the `Product` model. But for certificate product, this property is only computable from a CourseProductRelation point of view. So we revamp this feature to move this property from the `Product` model to the `CourseProductRelation`.

👔(backend) move `is_withdrawable` to course product relation

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/utils/course_run/__init__.py
src/backend/joanie/core/utils/course_run/aggregate_course_runs_dates.py
src/backend/joanie/core/utils/course_run/get_course_run_metrics.py
src/backend/joanie/tests/core/models/order/test_schedule.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/core/test_models_course_product_relation.py
src/backend/joanie/tests/core/utils/course_run/test_aggregate_course_run_dates.py
src/backend/joanie/tests/core/utils/course_run/test_get_course_run_metrics.py
src/backend/joanie/tests/core/utils/test_contract_definition_generate_document_context.py
src/backend/joanie/tests/core/utils/test_issuers_contract_definition_generate_document.py

Currently, when processing product payment schedule or withdrawable state, under
the hood, we aggregate all related course runs no matter its state. In some
case, this could lead to wrong computation particularly for certificate product
as user are purchasing this kind of product for a given enrollment. So
including archived runs in this case were weird. In order to fix, we improve
the method to aggregate course run dates of a product / course by adding an
argument to allow to ignore archived runs during aggregation.

👔(backend) ignore archived runs to process payment schedule and withdraw

---

src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/core/test_models_order.py

A target_course factory sometimes builds an archived one. This leads to a failing test.
Use future start and end dates.

✅(backend) fix flaky order model test

---

CHANGELOG.md
src/backend/joanie/core/enums.py
src/backend/joanie/core/factories.py
src/backend/joanie/core/flows/order.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/utils/payment_schedule.py
src/backend/joanie/payment/backends/base.py
src/backend/joanie/tests/core/models/order/test_factory.py
src/backend/joanie/tests/core/test_api_admin_orders.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/core/test_utils_payment_schedule.py
src/backend/joanie/tests/payment/test_backend_base.py
src/backend/joanie/tests/payment/test_backend_dummy_payment.py
src/backend/joanie/tests/swagger/admin-swagger.json
src/backend/joanie/tests/swagger/swagger.json
src/backend/pyproject.toml
src/mail/mjml/order_refunded.mjml
src/mail/mjml/partial/installment_table.mjml

We need to send an email to users when their order is refund.
Also, pending installment, must appear as canceled.
Wait for all installments to be refund before sending an email

Refund mail

---

.circleci/config.yml

CircleCI has recently updated its OS and this leads to some issue
related to concurrency with pylint. But a workaround exists to count
available cpu cores. We take opportunity to also use this value in our test-front job.
https://discuss.circleci.com/t/docker-executor-infrastructure-upgrade/52282/11

💚(circleci) count available cpu cores

---

src/backend/joanie/tests/core/utils/test_issuers_contract_definition_generate_document.py

We expect a date format that should not contain minutes for full hours. ie: 2 am instead of 2:00 am

✅(backend) fix date format in test

---

CHANGELOG.md
src/backend/joanie/core/api/admin/enrollment.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_admin_enrollments.py
src/backend/joanie/tests/core/test_models_course_run.py
src/backend/joanie/tests/core/test_models_enrollment.py
src/backend/joanie/tests/swagger/admin-swagger.json

Previously, admin (staff) users couldn't create or update enrollments for closed course runs. Now, they can because we've enhanced the admin API to allow this. The client API's serializers (student side) still enforce the old logic, blocking enrollments on closed course runs for regular users, while granting admin users this new capability.
Staff users should be able to create/update enrollment on closed runs. Regular users should still be blocked if they try to enroll to this kind of runs.

✨(backend) Authorize enrollment creation/update by admin on closed course runs

---

CHANGELOG.md
src/backend/joanie/core/filters/admin/__init__.py
src/backend/joanie/tests/core/api/admin/orders/test_list.py
src/backend/joanie/tests/swagger/admin-swagger.json

The purpose is to allow the the admin users to filter the order list by product type. They can choose one product type, or apply multiple product types to limit their order list.

✨(backend) Backoffice - Filter order list view per product type

---

CHANGELOG.md
src/backend/joanie/core/filters/admin/__init__.py
src/backend/joanie/tests/core/api/admin/orders/test_list.py
src/backend/joanie/tests/swagger/admin-swagger.json

Staff user want to be able to filter the orders by created_on dates.
For now, the `OrderAdminFilterSet` has more filters on the field `created_on` :
- filter by **exact** date of creation
- filter with **date range** of creation : 
- Use only the parameter `created_on_date_range_before` to query for dates equal or before
- Use only the parameter `created_on_date_range_after` to query for dates equal or after
- Use both parameters to filter within a date range.

:sparkles:(backend) Backoffice - Filter order list view per creation date

---

CHANGELOG.md
src/backend/joanie/core/templates/certificate/verify.html

Currently, Certificate verification page are indexed, we don't want that so we had a meta tag to explicit ask crawler to ignore those pages.

🔍(backend) prevent cert verification page indexation

---

CHANGELOG.md
src/backend/joanie/core/models/certifications.py
src/backend/joanie/tests/core/test_api_certificate.py

Before, the Certificate API endpoint for client returns certificate sorted by creation date (created_on). 
Now, they are sorted by the field `issued_on` date in descending order (most recent first).

✨(backend) Certificate API Endpoint - sort certificates by `issued_on` date field

---

CHANGELOG.md
src/frontend/admin/src/components/templates/certificates-definitions/inputs/RHFCertificateDefinitionTemplate.tsx
src/frontend/admin/src/components/templates/contract-definition/form/ContractDefinitionForm.tsx
src/frontend/admin/src/components/templates/contract-definition/inputs/RHFContractDefinitionName.tsx
src/frontend/admin/src/services/api/models/ContractDefinition.ts
src/frontend/admin/src/services/factories/contract-definition/index.ts
src/frontend/admin/src/services/repositories/contract-definition/ContractDefinitionRepository.ts
src/frontend/admin/src/tests/contract-definitions/ContractDefinitionTestScenario.ts
src/frontend/admin/src/tests/contract-definitions/contract-definition.test.e2e.ts
src/frontend/admin/src/tests/mocks/contract-definitions/contract-definition-mocks.ts
src/frontend/admin/src/tests/product/product.test.e2e.ts
src/frontend/admin/src/utils/string.ts

We recently create a new contract template. From now, there was only one, so the contract definition edit view in the back office application did not display input for this field.

✨(backoffice) add template name field into ContractDefinition edit view

---

CHANGELOG.md
src/backend/joanie/core/filters/admin/__init__.py
src/backend/joanie/tests/core/api/admin/orders/test_list.py
src/backend/joanie/tests/core/test_api_certificate.py

A test about order filtering on creation date was flaky, it was about results ordering. 
While digging for a fix, it appears that when we filter on a date, only orders created at 0:00 were found.
Also, a Django deprecation about datetime_safe was raised.

Fix order filter date

---

src/backend/joanie/tests/core/api/order/test_create.py

Useless assertions were done : target_courses comparison is already done in the response assert.

✅(backend) fix flaky order create test

---

CHANGELOG.md
src/backend/joanie/lms_handler/backends/moodle.py
src/backend/joanie/tests/core/test_commands_generate_certificates.py

We expect that the method `get_grades` of an lms backend returns a dict with boolean property `passed`. Currently for moodle, due to a transformation made by
moodlepy, the passed property has an integer value (0 or 1). We aim to fix
that into moodlepy directly but to fix the issue as soon as possible we first
cast the integer value as a bool.

🐛(moodle) fix `get_grades` method

---

CHANGELOG.md
src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductFormTargetCoursesSection.tsx
src/frontend/admin/src/tests/product/product.test.e2e.ts

Currently, when a target course is created, the `is_graded` field is not bound so no matter the value of this field, the target course is never graded by default and the editor has to edit the target course to change that...

🐛(backoffice) fix an issue on target course creation

---

CHANGELOG.md
src/frontend/admin/src/components/presentational/dnd/DndDefaultRow.tsx
src/frontend/admin/src/components/presentational/translatable-content/TranslatableForm.tsx
src/frontend/admin/src/components/testing/presentational/translatable-content/TranslatableContent.spec.e2e.tsx
src/frontend/admin/src/contexts/i18n/TranslatableFormProvider/index.tsx
src/frontend/admin/src/contexts/i18n/TranslationsProvider/TranslationsProvider.tsx

In order to make internationalized request to our API, we can't keep the `django_language` cookie as this one, once send in the request has the priority over the header 'Accept-Language'. So that's why when we need to make internationalized request, we have to remove this cookie, make the request then restore it. Our mechanims currently works pretty well until we have several TranslatableForms rendered on the same page. As when this kind of component is unmount we restore the cookie value, when there were several all was messed up! So we had a new TranstableFormProvider in charge to register all TranslatableForm mounted and restore/backup cookie value only when it's needed.

🐛(backoffice) allow to use nested TranslatableForm

---

CHANGELOG.md
src/backend/joanie/core/factories.py
src/backend/joanie/core/management/commands/delete_stuck_orders.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/utils/order.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/test_command_delete_stuck_orders.py
src/backend/joanie/tests/core/utils/test_utils_order.py

We have encountered some issues in the affectation of students to organization when they enroll. We have discovered that the orders in states `to_sign` and `signing` were causing that effect. Those orders exist because students have decided not to complete the process to sign the contract, and the order would stay in that state. The issue is that it takes one available seat on the session. We have added a django command that is responsible to clean up those orders that are considered as stuck. We also added the deletion of orders for product type certificate where the student opened the sales tunnel to purchase the certificate but never entered their payment information. To avoid this in the future, we have added a minimum time limit of tolerance on the latest update of those objects. If …

✨(backend) delete orders that are stuck in specific states

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/tests/core/api/order/test_create.py

In some case, it appears that the organization with the least orders count is not the one assigned. It appears that the queryset to count the order may return wrong results according if the related organization is implied as author is other course product relations with active orders.

🐛(backend) fix auto organization assignment to order logic

---

src/tray/templates/services/app/cronjob_delete_stuck_orders.yml.j2
src/tray/vars/all/main.yml

We have to add a cronjob in the tray to manage the delete_stuck_orders management command.

🔧(tray) add cronjob for delete_stuck_orders management command

---

CHANGELOG.md
src/backend/joanie/core/serializers/admin.py
src/backend/joanie/tests/core/api/admin/orders/test_list.py
src/backend/joanie/tests/swagger/admin-swagger.json

On the backoffice, we recently add a new column to display `updated_on` of an order. But currently, the api endpoint does not return this field so the view were broken.

🐛(backend) add missing `updated_on` field to AdminOrderLightSerializer

---

CHANGELOG.md
src/backend/joanie/payment/backends/lyra/__init__.py
src/backend/joanie/tests/payment/test_backend_lyra.py

When we check for installment payment after retrying, the response wasn't correctly handled.
Handle the response as if the initial payment request returned a response.

🐛(backend) fix installment update

---

CHANGELOG.md
docs/explanation/lms-connection.md
docs/moodle.md
env.d/development/common.dist
src/backend/joanie/core/utils/__init__.py
src/backend/joanie/settings.py
src/backend/joanie/tests/core/utils/configuration_fields/test_lms_backends_field.py

Currently, LMS Backends list is hardcoded in joanie settings. This is weird as if we want to setup new LMS that means we have to update those settings then make a release. Furthermore, it is also weird from an Open Source point of view as this settings is not overridable easily. So in order to fix that, we now allow to set all LMS backend configuration through a JSON array string environment variable.
**If you are a Joanie developer, you may have to update our `env.d/common` file to remove old LMS env vars and add the new `JOANIE_LMS_BACKENDS`. Take a look at `env.d/common.dist` as an example.**

🔧(backend) Allow to configure JOANIE_LMS_BACKENDS through env var

---

CHANGELOG.md
src/backend/joanie/payment/models.py
src/backend/joanie/tests/payment/test_models_credit_card.py

When a credit card is deleted, a post_delete signal is triggered to also remove the registered card from the payment provider. Currently, if this request fails,
the credit card deletion transaction is rollback. In order to prevent that, we
catch `PaymentProviderAPIException` and just log the error with useful
information to remove credit card information later from the payment provider.

🥅(backend) catch payment provider api error on credit card deletion

---

CHANGELOG.md
src/backend/joanie/core/flows/order.py
src/backend/joanie/core/management/commands/cleanup_credit_cards.py
src/backend/joanie/core/utils/emails.py
src/backend/joanie/payment/backends/base.py
src/backend/joanie/payment/backends/dummy.py
src/backend/joanie/payment/models.py
src/backend/joanie/tests/core/api/admin/orders/test_refund.py
src/backend/joanie/tests/core/api/admin/orders/test_retrieve.py
src/backend/joanie/tests/core/api/order/test_cancel.py
src/backend/joanie/tests/core/models/order/test_factory.py
src/backend/joanie/tests/core/test_command_cleanup_credit_cards.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/core/utils/test_emails_prepare_context_data.py
src/backend/joanie/tests/payment/test_backend_base.py
src/backend/joanie/tests/payment/test_models_credit_card.py
src/mail/mjml/order_refunded.mjml

When an order is completed, if their credit card  isn't needed, we want to delete it.

🔒️(backend) delete credit card

---

renovate.json
src/backend/pyproject.toml

Since the version 1.36, boto3 storage is no more compatible with our third party
storage S3 like... Currently the only way to fix that is to rollback to the
version 1.35.x
https://github.com/boto/boto3/issues/4409

📌(backend) pin boto3 to version less than 1.36

---

src/backend/joanie/payment/backends/lyra/__init__.py
src/backend/joanie/payment/exceptions.py
src/backend/joanie/tests/payment/test_backend_lyra.py

When we check for installment payment to lyra server, if we get a PSP_010 error, we want to consider the payment as unpaid.
Fixes #1048

🐛(backend) fix lyra is_already_paid

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/api/organizations/test_api_organizations_course_product_relations.py
src/backend/joanie/tests/core/test_api_course_product_relations.py
src/backend/joanie/tests/swagger/swagger.json

Since is_active is now a property that is handle by admin users only, there is no need that the field and value is present 
into the client serializer of OrderGroup. What is more import for the client side, is the value `is_enabled` of an order group.

:sparkles: (backend) remove `is_active` in order group client serializers

---

CHANGELOG.md
src/backend/joanie/core/models/certifications.py
src/backend/joanie/tests/core/utils/test_issuers_certificate_document.py

We had an issue with the internationalization of the verification view of certificates. Some part of the iframe were not translated into the current language and was using django's defaut language code instead.
Now, by wrapping the generation of the context of a certificate with the requested language, the templates are translated as expected and not using the default language in django settings when the translation exists.

🐛(backend) certificate verification view internationalization

---

CHANGELOG.md
arnold.yml
src/backend/pyproject.toml
src/frontend/admin/package.json
src/mail/package.json
src/openApiClientJs/package.json
src/tray/tray.yml
src/tray/vars/all/main.yml

Bump joanie to 2.17.0
- Add `start` and `end` datetime fields on order group model
- Add Sarbacane newsletter client
- Remove `generate_certificates` action in django admin views
- Remove `owner` and `is_main` in CreditCard model permanently
- Remove `is_active` on order group client serializer
- Internationalization of certificate verification view
- BO: generate certificates for orders with product of type certificate

🔖(chore) bump to 2.17.0

---

src/backend/joanie/core/utils/newsletter/sarbacane.py
src/backend/joanie/settings.py

Increase the backoff factor for Sarbacane GET requests from 0.1 to 0.25 to expand delay between retry.
https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html?highlight=backoff_factor

🔧(backend) adjust Sarbacane retry backoff factor

---

CHANGELOG.md
src/backend/joanie/core/apps.py
src/backend/joanie/core/enums.py
src/backend/joanie/core/models/courses.py
src/backend/joanie/core/models/products.py
src/backend/joanie/core/signals.py
src/backend/joanie/core/utils/webhooks.py
src/backend/joanie/tests/core/test_models_course_run.py
src/backend/joanie/tests/core/test_models_product.py
src/backend/joanie/tests/core/test_signals.py

From Richie we recently add new fields to CourseRun models to set offer available on the CourseRun. As in Joanie we are able to set the course run offer according to product linked to the related course, we update the course synchronization to add this information.

✨(backend) bind course offer into course webhook payload

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/utils/organization.py
src/backend/joanie/tests/core/api/order/test_create.py
src/backend/joanie/tests/core/utils/test_utils_organization.py

Currently only orders with inactive states (canceled, draft, assigned) were ignored in the organization assignation logic. But orders pending for signature or without payment method  are take in account but most of time this kind of orders are abandoned. So it has been ask to ignore this kind of order during assignation. Furthermore, we did not ignore refunded and refunding orders.
Resolve #1081

👔(backend) update organization assignation logic

---

src/backend/joanie/tests/core/api/order/test_create.py
src/backend/pyproject.toml

A new release of the package `fancycompleter` that we use for tab completion during breakpoints in tests was causing our circleCi [task](https://app.circleci.com/pipelines/github/openfun/joanie/9796/workflows/9c2d28df-e513-4d24-8b1d-33eb76f259bd/jobs/128219) to run tests to never execute. The [latest](https://pypi.org/project/fancycompleter/) release was done on the 13th of April 2025.
Fixed a flaky test due to latest change on assignation logic of organization on a new order.
Fix a failing flaky unit test that used the random module when it prepared the testing data. It was important to fix it because it is revealing how the auto assignation of an organization is on an order when the product has no fee. Also, we have changed the logic behind the assignation method, we needed to reflect …

✅(backend) fix failing test on auto assignation of organization

---

src/backend/joanie/tests/core/test_api_enrollment.py
src/backend/joanie/tests/core/test_flows_order.py
src/backend/joanie/tests/lms_handler/test_backend_openedx.py

If COURSE_WEB_HOOKS is defined locally in env.d/development/common, tests will fail.
Overriding prevents this.

✅(backend) add COURSE_WEB_HOOKS configuration to test cases

---

src/backend/joanie/core/api/admin/__init__.py
src/backend/joanie/core/factories.py
src/backend/joanie/tests/core/test_api_admin_users.py

We have a flaky test (`test_admin_api_user_list_filter_by_id`) on the CI where the results are not sorted the expected way. To have more consistency overtime, we have decided to sort the result of the list endpoint by `username`.
We also have another flaky test (`test_api_admin_orders_course_retrieve`) that happens rarely, it's with the `OrderGroup` factory. If we don't set a number of seat,
it can choose a number between **0 to 100** for this value. The issue is that when it sets 0 for the number of seats and we try to create an order on that order group, it would block the creation. To avoid this behavior, we have decided that the factory can choose a value between **1 to 100** if no value is setted during creation.

✅(backend) fix flaky tests

---

CHANGELOG.md
src/backend/joanie/core/templates/issuers/contract_definition_default.html
src/backend/joanie/tests/core/test_api_contract_definitions.py

For legal purposes, we move the dynamic content of the course section from of the contract definition the contract's body.
Those informations have become the **Article 1** of that body of the contract.
Once this development is deployed into the next release, you should increment by +1 your list of articles that you have set in the contract definition body.
Preview of the new structure: [unicamp_new_contract_definition_structure.pdf](https://github.com/user-attachments/files/20838476/unicamp_new_contract_definition_structure.pdf)

✨(backend) new structure for contract definition

---

src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/core/serializers/client.py
src/backend/joanie/tests/core/test_api_offerings.py
src/backend/joanie/tests/swagger/swagger.json

We need to return into the response of this endpoint the difference made with the voucher code or
the discounted price on the offering from its initial price. Now, this endpoint returns respectively, the initial price, the discount applied if one is set and finally the discounted price. If no discount, nor voucher code is set, it return a value for the initial price and sets None for the other two keys (`discount` and `discounted_amount`).

✨(backend) improve payment schedule endpoint

---

CHANGELOG.md
src/backend/joanie/core/api/client/__init__.py
src/backend/joanie/tests/core/test_api_offerings.py
src/backend/joanie/tests/swagger/swagger.json

For more clarity and since the endpoint payment schedule returns more informations about the payment plan of an offering, we have decided to change the name of this endpoint. It did not make anymore sense to keep it called that way, so now, it has been renamed to `payment-plan`.

🚚(backend) rename payment schedule endpoint to payment plan

---

src/backend/joanie/core/utils/offering.py
src/backend/joanie/tests/core/test_utils_offering.py

Changed log level from `DEBUG` to `INFO` for better visibility during offering synchronization.

🔊(backend) update log level in offerings sync

---

CHANGELOG.md
src/backend/joanie/core/utils/emails.py
src/backend/joanie/tests/core/utils/test_emails_prepare_context_data.py

Since we have introduced discounts on orders, the email that summarizes the installments paid or refused would still show the total representing the product's price instead of the order's total when a discount was applied. Now, the behavior as changed, we will always show the order's total instead.
Fix #1179

🐛(backend) fix installment email total when discounted price

---

CHANGELOG.md
src/backend/joanie/core/api/admin/__init__.py
src/backend/joanie/core/models/products.py
src/backend/joanie/tests/core/api/admin/batch_order/test_confirm_bank_transfer.py
src/backend/joanie/tests/core/api/admin/batch_order/test_confirm_purchase_order.py
src/backend/joanie/tests/core/api/admin/batch_order/test_confirm_quote.py
src/backend/joanie/tests/swagger/admin-swagger.json

Our Admin API `BatchorderViewset` requires some actions that be triggered by an admin user. Confirming the quote, confirming the purchase order, and confirming the bank transfer are not yet implemented.

:sparkles:(backend) admin api batch order actions

---

CHANGELOG.md
src/backend/joanie/core/templates/issuers/microcredential_degree_default.css
src/backend/joanie/core/templates/issuers/microcredential_degree_unicamp.css
src/backend/joanie/tests/testing_utils.py

Fixes #1203 
The current micro-credential templates do not fully match the design provided by the COM Department.
Several alignment issues need to be corrected, visible in both the UniCamp and default templates.
In both templates:
In the default template:
New designs below 
[certificate_unicamp.pdf](https://github.com/user-attachments/files/22424428/certificate_unicamp.pdf)
[certificate_default.pdf](https://github.com/user-attachments/files/22424430/certificate_default.pdf)

💄Fix style issues in default and unicamp micro credentials
